### ISSUE TITLE
dce inline doesn't work

### ISSUE THREAD

**Issue by celmedia** [FriendsOfTYPO3/frontend_editing#152]
im not sure if its my configuration ... but maybe somene has a other idea of what to inser in tabel="" field="" uid=""

	<core:contentEditable table="tt_content" field="pi_flexform" uid=" {contentObject.uid}">
	{field.test}
	</core:contentEditable>

any ideas or solutions? or is it a new task/feature?

**Comment by MattiasNilsson** [comment]
@celmedia Take a look at this example: https://raw.githubusercontent.com/FriendsOfTYPO3/frontend_editing/master/Documentation/NewContentElements/Index.rst

**Comment by celmedia** [comment]
doesnt work yet ... but we allready got the normal edit icons running with this module here from igor: 
https://github.com/igokruglov/typo3_dce

**Comment by MattiasNilsson** [comment]
Not relevant anymore.
