### ISSUE TITLE
If a headline has more than 50 characters editor shows wrong stuff

### ISSUE THREAD

**Issue by mediaessenz** [FriendsOfTYPO3/frontend_editing#162]
If you have a headline like "Anleitung zum Ändern der FTP- und Plesk-Zugangsdaten" (52 characters) I get this result:

One line with the text cut off after 50 characters and a ..."> at the end:
Anleitung zum Ändern der FTP- und Plesk-Zugangsdat...">

An other line with the full text, but with wrong edit possibilities (like for the bodytext)
Anleitung zum Ändern der FTP- und Plesk-Zugangsdaten

**Comment by MattiasNilsson** [comment]
A new release with the fix have been published: https://github.com/FriendsOfTYPO3/frontend_editing/releases/tag/v1.0.5
