### ISSUE TITLE
Moving an element does not create a log entry

### ISSUE THREAD

**Issue by sbusemann** [FriendsOfTYPO3/frontend_editing#171]
If I move a content element in the frontend, no sys_history entry is created.

**Comment by MattiasNilsson** [comment]
Hi @sbusemann I have been investigating this and the behaviour is exactly as if you move content elements around in the backend. We are using the DataHandler so it´s most likely related to a "bug" in TYPO3 Core. I will therefore close this ticket, thanks for your feedback 👍
