### ISSUE TITLE
iFrame javascript is not loaded

### ISSUE THREAD

**Issue by webian** [FriendsOfTYPO3/frontend_editing#176]
The javascript of the website is not loaded when frontend editing is enabled.

**Comment by webian** [comment]
If I revert this https://github.com/FriendsOfTYPO3/frontend_editing/pull/174 the javascript is loaded.

**Comment by webian** [comment]
The problem is that:
> inserting HTML content in the DOM using innerHTML, script tags inside it will not load or run. This applies to both inline scripts and external ones using the src attribute. https://ghinda.net/article/script-tags/

There are some hack to run the scripts but they have drawbacks.

**Comment by MattiasNilsson** [comment]
@webian Thanks for your bug report and thorough check up! It should now been fixed with this commit: https://github.com/FriendsOfTYPO3/frontend_editing/commit/b998e29fa29f92e13db7820f7c9443dea9cdf54c
