### ISSUE TITLE
Drag&drop of new content element not working

### ISSUE THREAD

**Issue by webian** [FriendsOfTYPO3/frontend_editing#179]
Drag&drop of new content element works only for the first element created on a page.
Once the first element has been created, trying to drop another element and there's no more the drop area in the page.

**Comment by webian** [comment]
This bug seems to happen when fluid_styled_content is not activated so this Typoscript of EXT:frontend_editing is not parsed and consequently edit icons and drop zones are not rendered in the HTML:
```
lib.fluidContent {
    stdWrap {
        editIcons = tt_content:header
    }
}
```

If possible, remove this dependency of frontend_editing from fluid_styled_content or document the fact that, if fluid_styled_content is disable, the Typoscript of `editIcons` must be set manually.

**Comment by JensHH** [comment]
sorry, what exactly does this mean? I'm not using fluid_styled_content and encounter the same problem. Do I have to put those lines and if, where do I have to put these lines. I tried in the setup of my root template, but it did not work
