### ISSUE TITLE
frontend_editing in translated page

### ISSUE THREAD

**Issue by webian** [FriendsOfTYPO3/frontend_editing#182]
Editing a record/field in a translated page results in the record/field be edited in the default language.

**Comment by erredeco** [comment]
I can guess that the reason lies here: for example:

```
<core:contentEditable table="pages" field="title" uid="{data.uid}">
        <h1>{data.title}</h1>
</core:contentEditable>
```
This saves the title in the _pages_ table, **but** the translated pages are saved in _pages_language_overlay_

I tried, using VHS, to write:

```
<f:if condition="<v:page.language /> == 0">
  <f:then>
    <core:contentEditable table="pages" field="title" uid="{data.uid}">
      <h1>{data.title}</h1>
    </core:contentEditable>
  </f:then>
  <f:else>
    <core:contentEditable table="pages_language_overlay" field="title" uid="{data.uid}">
      <h1>{data.title}</h1>
    </core:contentEditable>  
  </f:else>

</f:if>
```

but no luck

**Comment by tripbe** [comment]
sth like this inline if condition

`<core:contentEditable table="tt_content" field="bodytext" uid="{f:if(condition: '{data._LOCALIZED_UID}', then: '{data._LOCALIZED_UID}', else: '{data.uid}')}"><f:format.html>{data.bodytext}</f:format.html></core:contentEditable>`

seems to work for me in 9.5.
