### ISSUE TITLE
Messed image manipulation

### ISSUE THREAD

**Issue by webian** [FriendsOfTYPO3/frontend_editing#200]
The image manipulation editor is not usable.

**Comment by MattiasNilsson** [comment]
Do you mean in the modal, when using the backend form?

**Comment by webian** [comment]
I mean the crop tool:
![](https://i.imgur.com/RN6MfjB.jpg)

**Comment by yar-trach** [comment]
Can be closed

**Comment by MattiasNilsson** [comment]
Solved with: #207
