### ISSUE TITLE
Empty fields should have height=0

### ISSUE THREAD

**Issue by webian** [FriendsOfTYPO3/frontend_editing#202]
If frontend editing is enabled then the empty fields in the page occupy a vertical space:
![](https://i.imgur.com/dfm0zaS.jpg)
while, when frontend editing is disabled, the elements will look like this:
![](https://i.imgur.com/iajWopV.jpg)

To have a better overview of how the page will look even with frontend editing enabled, the empty fields should have height=0 until an hover occurs.

**Comment by webian** [comment]
By better examining this problem, I noticed that the problem arises from the fact that frontend_editing saves a "new line" character in the database when the editor deletes all the characters in a field.

This "new line" character is then transformed into a <br> in the HTML, and then the field is displayed at a non-zero height. This on one hand is fine because the publisher can edit the field, but on the other is not good because the content element is not visually as it really is.

The optimum would be that an empty field is displayed at a non-zero height only at roll-over.

**Comment by MattiasNilsson** [comment]
Fixed by: #246

**Comment by webian** [comment]
@MattiasNilsson also this issue seems not to be fixed by the commit https://github.com/FriendsOfTYPO3/frontend_editing/pull/246/commits/9927e15bb3fdac17c1e5e8b0aab8e63794ff8a67 that instead adds weird behaviours because of https://github.com/FriendsOfTYPO3/frontend_editing/pull/246/commits/9927e15bb3fdac17c1e5e8b0aab8e63794ff8a67#diff-368a2df44facc11b3fdb3cb6c02d8c67R44 that causes the header to go from centered to left on CE hover, like this:
![](https://i.imgur.com/DZRRGXX.jpg)
