### ISSUE TITLE
Improve drop zone active

### ISSUE THREAD

**Issue by webian** [FriendsOfTYPO3/frontend_editing#205]
As a small UI improvement we could make the active drop zone green instead of expand it vertically.
This is better because when we alter the flow of DOM elements (in this case expanding the drop zone height on rollover) the user gets a bit confused.

From this:
![](https://i.imgur.com/lQQFW8m.jpg)

To this:
![](https://i.imgur.com/iIXVmyQ.jpg)

**Comment by MattiasNilsson** [comment]
@webian I do not actually get why green should be a better solution? We are using the TYPO3 orange for branding.

**Comment by webian** [comment]
@MattiasNilsson what I mean is to use another color (i.e. green) for the roll-over in the drop zone instead of expanding the drop zone vertically. I don't mean to change all the drop zones in green.

**Comment by MattiasNilsson** [comment]
@webian Ok got it thanks! 👍
