### ISSUE TITLE
Inline editing in edit panels is clunky

### ISSUE THREAD

**Issue by atomicptr** [FriendsOfTYPO3/frontend_editing#212]
Not sure if "edit panel" is the correct terminology for this, I mean these fields here:

![edit panel](https://user-images.githubusercontent.com/674705/27375975-0c00148e-5671-11e7-965a-0059bb5156e6.png)

The issue is, enabling inline editing in one of those edit panels is currently extremely clunky. You can't select text with the mouse (as dragging will move the element) and you can't move the cursor (except with arrow keys). I made a small gif to illustrate this problem:

![problem](https://user-images.githubusercontent.com/674705/27376050-4936c3f2-5671-11e7-84e3-2153c31da480.gif)

**Comment by pxamike** [comment]
@atomicptr Could you specify which browser you tested in?

**Comment by atomicptr** [comment]
Firefox
