### ISSUE TITLE
Path for icons of CE, Grid Elements and some plugins may be broken.

### ISSUE THREAD

**Issue by pxamike** [FriendsOfTYPO3/frontend_editing#225]
See image.

![frontend-editing-icons](https://user-images.githubusercontent.com/12510409/28609424-ed826b6c-71e4-11e7-8614-54d11e908149.png)

**Comment by erredeco** [comment]
+1 happened to me, too

**Comment by yar-trach** [comment]
I have fixed GridElements and NewsExt icons in this branch, but there left to fix CE icons. So, WIP for now.
https://github.com/FriendsOfTYPO3/frontend_editing/tree/icon_path
