### ISSUE TITLE
Save option in notification of unsaved changes

### ISSUE THREAD

**Issue by webian** [FriendsOfTYPO3/frontend_editing#236]
Offer to save directly in the popup that notify the editor of unsaved changes.
Practically add a "Save" button to the popup.

**Comment by MattiasNilsson** [comment]
This have already been implemented, see screenshot.

<img width="751" alt="Skärmavbild 2021-02-05 kl  09 05 54" src="https://user-images.githubusercontent.com/1718315/107006498-7d988b00-6791-11eb-9c54-decff5be390a.png">
