### ISSUE TITLE
With deactivated frontend_editing internal links in frontend have t3://page?uid= syntax

### ISSUE THREAD

**Issue by mediaessenz** [FriendsOfTYPO3/frontend_editing#240]
To reproduce:
1. Install frontend_editing extension, but do **not** activate it in your user settings.
2. Login to the backend and open a page in the frontend, containing an internal link, generated with the link wizard of the ckeditor.
3. All this links starts with t3://page?uid= and don't work anymore
4. After logout from the backend and reloading the page in frontend, all links are right and working again

**Comment by erredeco** [comment]
I had a similar issue with 8.7.7, but only links made via linkhandler seemed affected.

**Comment by MattiasNilsson** [comment]
This is solved with the release of version 1.2.
