### ISSUE TITLE
Do not reload the page when no changes have been performed

### ISSUE THREAD

**Issue by Gloumi** [FriendsOfTYPO3/frontend_editing#252]
This is frustrating for the user to have a page reload after closing the edit modal box without having made any changes.
In a more general way, I think the entire page reload degrades the user experience.

**Comment by codesource** [comment]
+1 with both remarks

**Comment by pxamike** [comment]
The problem is how to communicate this from the iframe in the modal back to the frontend editor. It also has to work on different site roots (iframe may have a different domain).

**Comment by webian** [comment]
Duplicate of #214
