### ISSUE TITLE
New design

### ISSUE THREAD

**Issue by MattiasNilsson** [FriendsOfTYPO3/frontend_editing#258]
Implement the new design for the frontend editing.

![feedit-new](https://user-images.githubusercontent.com/1718315/32724551-fc9989a8-c871-11e7-8dcf-07bfba57600d.jpg)

**Comment by webian** [comment]
Please, consider to integrate frontend_editing inside the backend: https://github.com/FriendsOfTYPO3/frontend_editing/issues/191

**Comment by MattiasNilsson** [comment]
This is done and implemented since the release of release 1.3.0
