### ISSUE TITLE
frontend-editing "inception" when using solr search-fields

### ISSUE THREAD

**Issue by pxamike** [FriendsOfTYPO3/frontend_editing#259]
frontend_editing 1.2.4 + t3kit 2.4.0 with solr fluid templates.

When logged in as an editor and using frontend_editing in the frontend, if I make a search (in header-middle search-filed) and press enter, a frontend-editor within a frontend-editor appears along with the result. It's possible to do this as many times as you want to stack frontend-editors.

![frontend-editing inception](https://user-images.githubusercontent.com/12510409/32779280-60475810-c93d-11e7-8301-9232efceb896.png)

**Comment by mabolek** [comment]
@pxamike Any thoughts on what is causing this? It sounds like it is the server returning a new frontend editor in a JS request or that it's loading the frontend editor within one of the iframes.

**Comment by gfobe** [comment]
Same behaviour with frontend_editing v1.4.6 and ke_search v2.8.1 on TYPO3 v8.7.21.

**Comment by pxamike** [comment]
Still happens in frontend_editing v1.9.3 on TYPO3 v9.5.15.

**Comment by mabolek** [comment]
This issue is relating to XHR requests. The fix in v1.9.3 only fixes inceptions on redirects and link clicks. This is possibly a solution we can implement: https://stackoverflow.com/questions/10783463/javascript-detect-ajax-requests

**Comment by MattiasNilsson** [comment]
@pxamike Do you still have this issue and to reproduce it I must have Solr installed. Then also make sure that there is a global search field which sends to a result page?

**Comment by MattiasNilsson** [comment]
@gfobe How do you reproduce this issue in ke_search? I have it installed and do a POST with the following queryparams: ?`&tx_kesearch_pi1%5Bsword%5D=test+search&tx_kesearch_pi1%5Bpage%5D=1&tx_kesearch_pi1%5BresetFilters%5D=0`

The page still works and no Inception are being made.

![Skärmavbild 2021-02-25 kl  12 34 37](https://user-images.githubusercontent.com/1718315/109148157-266d5100-7766-11eb-95b4-f9d42cfcc3a6.png)
![Skärmavbild 2021-02-25 kl  12 34 41](https://user-images.githubusercontent.com/1718315/109148165-279e7e00-7766-11eb-9238-ea0c23499338.png)

**Comment by gfobe** [comment]
> How do you reproduce this issue in ke_search? I have it installed and do a POST with the following queryparams: ?`&tx_kesearch_pi1%5Bsword%5D=test+search&tx_kesearch_pi1%5Bpage%5D=1&tx_kesearch_pi1%5BresetFilters%5D=0`

Sorry, I don't know in detail and I'm far away of the project applying to in the past. But I think it was like reporter describes. On general frontend pages it works ok, but using the search page we have had stacked frontend-editors. We did not solved this issue, but I don't remember the workaround we used.

**Comment by MattiasNilsson** [comment]
@gfobe Thanks for your feedback, will continue to look into it!
