### ISSUE TITLE
Enable Frontend Editing always enabled (visually)

### ISSUE THREAD

**Issue by pxamike** [FriendsOfTYPO3/frontend_editing#266]
Login to BE, select User Settings, select "Edit and Advanced functions"-tab.

Independent of what actual state "Enable Frontend Editing" is in, visually it is always enabled. Tested in 1.2.4 (seems to be the same in 1.2.5 too).

![selection_082](https://user-images.githubusercontent.com/12510409/33768846-04b95a36-dc28-11e7-9f34-bb7968b71001.png)

**Comment by tim9413** [comment]
Fixed with theme_t3kit commit: https://github.com/t3kit/theme_t3kit/commit/caa9f74539b626cd6c2f7cea812c483420bda864
