### ISSUE TITLE
php error with viewhelper on certain page

### ISSUE THREAD

**Issue by pxamike** [FriendsOfTYPO3/frontend_editing#267]
Happens when frontend-editing is enabled on a certain startpage (ask me for details).

![selection_081](https://user-images.githubusercontent.com/12510409/33769135-4312cd70-dc29-11e7-86b9-9963c31ab8ba.png)

The same page also generates a blank-page when the frontend editing for the current BE-user is enabled and you visit the frontend editing the first time, so likely this behaviour may disappear also when the issue is fixed.

**Comment by MattiasNilsson** [comment]
Fixed with #265 265
