### ISSUE TITLE
IE11/Edge in windows 10 - draggable CE not working 

### ISSUE THREAD

**Issue by mesosa** [FriendsOfTYPO3/frontend_editing#272]
When dragging a content element from the right bar in IE11 or Edge, there are no drop zones present on the page.
On IE11 the draggable CE also gets a "disabled" icon as in it's not valid to drag it.
On edge it shifts between the "disabled" icon and the CE icon.

I am getting these errors in the console:

IE11:
```
HTML1114: Codepage unicode from (UNICODE byte order mark) overrides conflicting codepage windows-1252 from (13)

SCRIPT65535: Unexpected call to method or property access.
FrontendEditing.js (207,4)
```

Edge:

```
SCRIPT70: SCRIPT70: Permission denied

SCRIPT1168: Element not found.
FrontendEditing.js (206,3)
```

**Comment by mabolek** [comment]
IE (>= 11) and Edge are officially supported by TYPO3 v9 LTS, and so should frontend_editing. However, it won't be a priority. The community is welcome to help fix this issue.

**Comment by MattiasNilsson** [comment]
Closing this as IE 10 is ancient!
