### ISSUE TITLE
version 1.3.2 two issues 

### ISSUE THREAD

**Issue by helmut-winkelbach** [FriendsOfTYPO3/frontend_editing#278]
- white screen when load FE window, this is ok if you click button "Hidden elements"

- scroolbar at the right has no posibilitie to scroll down

**Comment by linnearad** [comment]
Can confirm the behavior  with blank screen on one site and not on two other. All running TYPO3 8.7.9 on Nginx. But two different servers.  

But the strange part is if I load a page one the first site, turn on hidden elements and wait for a bit (30 - 60 sec - haven't checked exactly), and then turn of hiden elements again - sometimes only hidden elements disappear - and the page isn't reloaded to a white page.

**Comment by DirkPersky** [comment]
I have the same Problem with white Screen
Typo3: 8.7.9
Frontend_editing: 1.3.2

**Comment by MacGeyer** [comment]
not nice but before official patch try to replace in frontend_editing/Classes/Hook/FrontendEditingInitializationHook.php line 161 "$requestUrl = $requestUrl . $urlSeparator . 'frontend_editing=true';" by "$requestUrl = $requestUrl . $urlSeparator . 'frontend_editing=true&no_cache=1';"

**Comment by MattiasNilsson** [comment]
A new release is out that fixes this problem: https://github.com/FriendsOfTYPO3/frontend_editing/releases/tag/v.1.3.3
