### ISSUE TITLE
Invalid request for route when accessing frontend as non-admin user

### ISSUE THREAD

**Issue by mabolek** [FriendsOfTYPO3/frontend_editing#281]
Accessing the frontend as non-admin user results in an exception:

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1425389455: Invalid request for route "/ajax/frontend-editing/editor-configuration" | TYPO3\CMS\Backend\Routing\Exception\InvalidRequestTokenException thrown in file /mnt/persist/www/sites_docroot/localhost/vendor/typo3/cms/typo3/sysext/backend/Classes/Http/RouteDispatcher.php in line 49. Requested URL: http://localhost/typo3/index.php?ajaxID=%2Fajax%2Ffrontend-editing%2Feditor-configuration&ajaxToken=965168c7ddd8ec2252f636bdcb3f5722e4acefd1&page=139&table=tt_content&uid=781&field=bodytext

**Comment by MattiasNilsson** [comment]
After checking and testing this I can verify that the problem do not exist anymore. @mabolek

**Comment by MattiasNilsson** [comment]
Fixed in previous versions.
