### ISSUE TITLE
Fontend-Login for Editors ?

### ISSUE THREAD

**Issue by HorstBaumann** [FriendsOfTYPO3/frontend_editing#282]
Do you know a workaround for TYPO 8.7.*,
to manage the necessary editor-login on the frontend
OR redirect certain editors directly to the frontend after the login ?

So an editor is able to use the frontend_editing without ever visiting the backend ?

In earlier versions (4.* - 6.2) I used the simulatebe-extension, but it doesn't support 8.*

For me this function is the missing piece to make your extension the perfect editing-method for editors,
which do not really need the backend and can skip it.

**Comment by MattiasNilsson** [comment]
Hi @HorstBaumann I would suggest that you take a look into this https://github.com/t3kit/theme_t3kit/blob/master/ext_localconf.php#L62

This makes is possible for the backend user to choose from a dropdown if they want to be redirected to fronted or backend when being logged in.

**Comment by HorstBaumann** [comment]
wow - you guys are really fast :-)
Great ! - Thanks a lot.
I totally forgot that this option is still part of the TYPO3-configuration.
(now I'm looking for a user specific setting to avoid the BackEnd-Option for certain editors...)
