### ISSUE TITLE
Links via RTE broken

### ISSUE THREAD

**Issue by klodeckl** [FriendsOfTYPO3/frontend_editing#287]
If the extension is installed, all t3:// links won’t get parsed, so in the frontend a href="t3:…" is shown.

I’m not the only one with that problem: https://stackoverflow.com/questions/48518869/typo3-internal-links-inserted-from-the-ckeditor-are-not-converted

**Comment by klodeckl** [comment]
Problem is in Configuration/TypoScript/setup.ts:
# prevent links from being parsed to FE url
lib.parseFunc_RTE.tags.a >

But why?

**Comment by cdaecke** [comment]
@MattiasNilsson @mabolek This changes seem to be overwritten by [this commit](https://github.com/FriendsOfTYPO3/frontend_editing/commit/f476b651406ca94768388e16be8d453fdaeeffc1), so the described problem still exists.
