### ISSUE TITLE
Pagetree in frontend editing interface is not shown

### ISSUE THREAD

**Issue by erredeco** [FriendsOfTYPO3/frontend_editing#289]
- Environment: TYPO3 8.7.10 on windows XAMPP machine (PHP 7.0)
- Installed EXT:frontend_editing 1.3.3

Result: the pagetree in frontend editing does not work (does not appear at all). I attach a screenshot of the javascript error

![cattura](https://user-images.githubusercontent.com/3647646/36894644-5e521620-1e0c-11e8-99d2-bc68fb0ae2a4.png)

**Comment by ameos** [comment]
Hello

Same problem for us.
No problem with TYPO3 8.7.9.

D3 library was updated for typo3 8.7.10 (for issue https://forge.typo3.org/issues/83741 i think).
