### ISSUE TITLE
Issue with 8.7.11 ?

### ISSUE THREAD

**Issue by adrienjacob** [FriendsOfTYPO3/frontend_editing#291]
Not sure if it's a problem from the core or frontend_editing, but since the last core update to 8.7.11, it seems absrefprefix is not applied correctly anymore (cf. missing slashes) :
![image](https://user-images.githubusercontent.com/22765183/37491660-e3196344-289e-11e8-9374-c8aef2b9caf1.png)
Maybe related to https://forge.typo3.org/issues/83630
and https://github.com/TYPO3/TYPO3.CMS/commit/0162ff19abffb3f12797ff100d6425b84ea68529

**Comment by adrienjacob** [comment]
Just tested 8.7.12 and same problem... am I the only one experiencing this ?

**Comment by adrienjacob** [comment]
thanks @MattiasNilsson

**Comment by MattiasNilsson** [comment]
@adrienjacob New release out: 
https://github.com/FriendsOfTYPO3/frontend_editing/releases/tag/v1.3.6
