### ISSUE TITLE
Translate the extension

### ISSUE THREAD

**Issue by GuillaumeGBzh** [FriendsOfTYPO3/frontend_editing#295]
Hello,

Is it possible to add the extension to the TYPO3 translation server?

Thanks

**Comment by MattiasNilsson** [comment]
@GuillaumeGBzh We have no plan to do it yet, but you can always start to translate these files: https://github.com/FriendsOfTYPO3/frontend_editing/tree/master/Resources/Private/Language

**Comment by GuillaumeGBzh** [comment]
It's Ok : https://translation.typo3.org/fr/TYPO3.ext.frontend_editing/

Thanks.

**Comment by Gu3** [comment]
@GuillaumeGBzh : How can I help ? I don't know where to sign up ...
