### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by typo3rel** [FriendsOfTYPO3/frontend_editing#298]
Hi,
with BS4 i can't drop elements to the dropzone(does not expand) in a flexbox container and the flexbox childs (col-4, col-6..) no longer behave normally through the t3-frontend-editing__ce  wrap.

![bildschirmfoto vom 2018-08-30 18-27-17](https://user-images.githubusercontent.com/42843748/44865607-15b9ee00-ac83-11e8-920f-49ee2e2a12dd.png)

![bildschirmfoto vom 2018-08-30 18-44-50](https://user-images.githubusercontent.com/42843748/44866180-ceccf800-ac84-11e8-9b9a-d7178d7ab758.png)
Thanks.

**Comment by MattiasNilsson** [comment]
As this one now works, I will close the task.
