### ISSUE TITLE
FrontEnd editing disappeared from TYPO3 v9 Roadmap

### ISSUE THREAD

**Issue by MacGeyer** [FriendsOfTYPO3/frontend_editing#300]
3 weeks ago FrontEnd editing was still planned to be integrated in TYPO3 v9.4 but not yet what is planned now ?
https://web.archive.org/web/20180812111304/https://typo3.org/cms/roadmap/

**Comment by georgringer** [comment]
To be able to ship 9 LTS in a good shape priority has been given to routing.

**Comment by Norcoen** [comment]
last commit: may, 2nd

project is dead

**Comment by MattiasNilsson** [comment]
@MacGeyer @georgringer @Norcoen The project is not dead at all! It has just been summer and some months focus on other things. But as I stated the project is NOT dead!

**Comment by MacGeyer** [comment]
@georgringer FE editing has already been removed from 8 LTS because everythings couldn't be managed from FE, and now FE editing has been removed from 9 LTS ! Can't believe in the Roadmap anymore ? 
Must have features are still missing [](https://github.com/FriendsOfTYPO3/frontend_editing/issues/284) in the extension ...

**Comment by jnugh** [comment]
Will the changes from https://review.typo3.org/#/c/57119/ be merged here to make the extension compatible with 9.x or will development continue directly as a sysext in the TYPO3 repos?

**Comment by mfvetter** [comment]
Will this extensions/feature also work with Workspaces?

**Comment by josefglatz** [comment]
The official info from yesterday @ MEET TYPO3 Vienna: **it‘s canceled for the 9 LTS as a sysext**. Until it is ready (you can follow the state in the mentioned gerrit patch a few comments before here in the issue) you have to use it like any other 3rd party extension.

**Comment by josefglatz** [comment]
@mvfetter: didn‘t tested so far. But you can test the pstch by your own. And leave a comment in the patch or forge issue if something isn‘t working ❤️
