### ISSUE TITLE
TYPO3 9.5/1.4.0 - Click on Edit Icon triggers JS-Error

### ISSUE THREAD

**Issue by tripbe** [FriendsOfTYPO3/frontend_editing#303]
When clicking on the Edit Icon a JS Error occurs:
Editor.js:112 
Uncaught TypeError: Cannot read property 'iframe' of undefined

Quick Fix:
changing following in Line 112 & 116 
from 
Modal.identifiers.iframe
to
Modal.Identifiers
fixes the issue for me. Not tested on 8.7, doubt it will work there.

see:
https://github.com/FriendsOfTYPO3/frontend_editing/compare/master...tripbe:patch-1

TYPO3 9.5
boostrap_package 10.0.2
frontend_editing 1.4.0

**Comment by randomresult** [comment]
Works for me as well until i use a site-configuration. 

When adding a site configuration it tries to load https://myinstall.local/TYPO3/CMS/Lang/Lang.js?bust=42735d74378516015f43b913fcc38546e1ba4c36

**Comment by Pistil-Studio** [comment]
@tripbe thx man. perfect for me :)
