### ISSUE TITLE
Changes over "header" field are written over "bodytext"

### ISSUE THREAD

**Issue by instruccionesaldorso** [FriendsOfTYPO3/frontend_editing#304]
Using a fresh new TYPO3 8.7.19 installation.
EXT:frontend_editing 1.4.0

- When changing a tt_content element with CType="text", if I modify through the frontend the header of that element and push "Save all" button on the top corner, the "header" field stays as it is, and the new changed header is being taken into the top of the field "bodytext".

- However, for a tt_content element with CType="header", the field "header" is overwritten with the new changes.

Did anyone have this same behaviour?

**Comment by ademas02** [comment]
I have the same problem. Also modifying bodytext, after saving the title appears also as a new line within the bodytext.

**Comment by MattiasNilsson** [comment]
@instruccionesaldorso @ademas02 Are you using some custom elements? I have problem replicating the issue.

**Comment by vruescas** [comment]
@MattiasNilsson if you edit the header of a bodytext content element direct on the page, not with the edit dialog, and saves the change the header is not updated in the content element, the new header is in the text field integrated. I hope this help.

**Comment by vruescas** [comment]
@MattiasNilsson i found the problem. All CType = "text" must replaced to textmedia.

**Comment by vruescas** [comment]
@MattiasNilsson i found a better the solution without change any on CType. The property "beforeLastTag = 1" must be set like "beforeLastTag = 0", so the FE plugin not set the content element editable.
