### ISSUE TITLE
Links to files point to root folder

### ISSUE THREAD

**Issue by JensHH** [FriendsOfTYPO3/frontend_editing#308]
There are some links to css and js files that point to the root directory instead of a subfolder

in my case http://localhost/typo3conf/ext/frontend_editing/Resources/Public/Css/frontend_editing.css?1540288996
should point to http://localhost/myProject/typo3conf/ext/frontend_editing/Resources/Public/Css/frontend_editing.css?1540288996
Same problem with:
backend.css
require.js
jquery.min.js

Other files are correct

**Comment by NKnuelle** [comment]
I have the same problem. Files are not referenced and because of that my frontend has no css styling and I don't see any content. Just the Button elements in a list with their function text. How can I change the URL manually?
