### ISSUE TITLE
ContentEditableViewHelper - Possibility to use <span> instead of <div>

### ISSUE THREAD

**Issue by GuillaumeGBzh** [FriendsOfTYPO3/frontend_editing#311]
Hi,

Depending on the template that you want to make editable, it should be possible to use the span tag instead of div.

**Comment by GuillaumeGBzh** [comment]
Hi @MattiasNilsson,

Why close this ticket so fast?
The need is there.

**Comment by MattiasNilsson** [comment]
The functionality is merged https://github.com/FriendsOfTYPO3/frontend_editing/commit/64917710c65ae5cf704ed019d2b86e38645e8fb8

**Comment by GuillaumeGBzh** [comment]
Sorry, I read wrong :)

Thank you for the configuration @MattiasNilsson.

But, it would be better to add a configuration at the Viewhelper level as well.
The tag to use depends on the integration frontend and therefore the template.

What do you think ?
