### ISSUE TITLE
Feature request: Copying pages in Site tree

### ISSUE THREAD

**Issue by FallenVixtah** [FriendsOfTYPO3/frontend_editing#313]
It would be great to be able to copy pages also in frontend edit, since many clients use this feature a lot when creating new pages in backend.

**Comment by webian** [comment]
https://github.com/FriendsOfTYPO3/frontend_editing/issues/191
^ this could resolve any feature request related to the page tree functionalities, but unfortunately it has been closed.

**Comment by kaystrobach** [comment]
and this would also ensure, that we have a consistent UI for the BE editors and the FE Editors.

**Comment by MattiasNilsson** [comment]
This will be solved in v2 of frontend editing as it is a backend module. Which now are using the native TYPO3 backend tree: https://github.com/FriendsOfTYPO3/frontend_editing/pull/434
