### ISSUE TITLE
popup doesnt open 

### ISSUE THREAD

**Issue by celmedia** [FriendsOfTYPO3/frontend_editing#314]
get an js error in the console when i try to open the editing popup lightbox. version 9.5.1 with 1.4.2
!
[unbenannt2](https://user-images.githubusercontent.com/24301935/49066157-88098280-f220-11e8-94f9-7f4814a0a9fa.JPG)
![unbenannt](https://user-images.githubusercontent.com/24301935/49066158-88098280-f220-11e8-96ba-a80f991bc2cd.JPG)

**Comment by einarsvan** [comment]
This is because Modal doesn't contain an `identifiers` property. 
Try changing Modal.identifiers.iframe to *Modal.types.iframe* here: 
https://github.com/FriendsOfTYPO3/frontend_editing/blob/master/Resources/Public/JavaScript/Editor.js#L111 and on line 116 as well. 

```
currentModal.find(Modal.types.iframe).on('load', function () {
  top.TYPO3.Backend = top.TYPO3.Backend || {};
  top.TYPO3.Backend.ContentContainer = {
    get: function () {
      return currentModal.find(Modal.types.iframe).get(0).contentWindow;
    }
  };
});
```
This seems to work...

**Comment by ZweisteinT** [comment]
Hey, 
yeah i had the same Problem. Modals didnt Show up.

So today i upgraded to GitHub Version. Now the modals Show up, but ist not fixed yet. In IE Edge, i get a loading Symbol over the upcoming modal and the loading never stops. 

FUN Fact: If you open the Sourcecode in EDGE at the same time, the modal Shows up as expected :D 
- Sourcecode Editor closed: Only persmission error.
- Sourcode Editor open: null reference

![fronteditor](https://user-images.githubusercontent.com/24483729/49237477-990fea80-f3fe-11e8-8d59-88e66d86abf0.png)
