### ISSUE TITLE
user/admins with other uid than 1 doesnt see edit icons

### ISSUE THREAD

**Issue by celmedia** [FriendsOfTYPO3/frontend_editing#316]
when you creat a new user the icons dont show ... eaven you make a admin user also dont work ... and also when put the admin on to the "System Maintainers" list... inline editing workes but not the icons

my version 9.5.1 1.4.3 

![unbenannt](https://user-images.githubusercontent.com/24301935/49210532-98a32f80-f3bd-11e8-8e96-8855b131119f.JPG)

it workes in 8.7.12 with 1.3.6

**Comment by einarsvan** [comment]
OK, so this might sound a bit weird, but here is a workaround.
Activate Admin Panel at the root of your site by setting 
`config.admPanel = 1`
Then, as the new user, open the admin panel in FE.
You should now see the edit icons.
You can now remove config.admPanel = 1 from the TS template again, and the icons should still be there.

This is def. a bug though...

**Comment by einarsvan** [comment]
Did a little digging, and though I'm not completely sure, this seems to be a TYPO3 core issue. The FrontendEditingPanel.php file doesn't get included at all, unless the user activates the admin panel at least once. So basically, EXT:frontend_editing depends on the user having access to AdminPanel and activating it. See workaround above. 

@MattiasNilsson You know anybody (core members, maybe) that could look into this?

**Comment by celmedia** [comment]
yeahhh ... that workaround workes at least great :-) thanks @einarsvan

**Comment by celmedia** [comment]
if its not a admin ... then i just change it to admin ... activate / deacktivate admpanel and switch back to a non admin usergroup and it also workes then ... so good :-)

**Comment by mabolek** [comment]
I'm closing this issue as setting `config.admPanel = 1` will fix it.

(It's a TYPO3 core issue, not an issue with this extension.)
