### ISSUE TITLE
text & image

### ISSUE THREAD

**Issue by ZweisteinT** [FriendsOfTYPO3/frontend_editing#317]
Hi,
I doesnt know if it is actually supposed to work, but:

When i have any Standard Fluid Content element with Images (Text&Image, Text&Media, Image), then the container in the frontend is Grey and i only can edit it using the modal.

When i have a text only element, then the container in the frontend is orange and i can edit it inline.

Is it a bug or expected? It would be cool if i can still edit the text inline and maybe change the Image in the modal later.

**Comment by ZweisteinT** [comment]
Seems that i can override the fluid templates (e.g. TextPic.html) and add <core:contentEditable> around the bodytext. Then i get a grey border around the whole container, but also i get an orange container within for the bodytext, that i can edit.

**Comment by mabolek** [comment]
Sounds like you have solved this issue. I'm closing it. If you think this is in error, please feel free to contact me.
