### ISSUE TITLE
CK-Editor Linkbutton with live-editing doesn't work

### ISSUE THREAD

**Issue by yurianu** [FriendsOfTYPO3/frontend_editing#321]
If you want to set a link in  your text with the live editing function, after clicking the link button the modal will show you the following typo3 error.
"Argument 2 passed to TYPO3\CMS\Core\Configuration\Richtext::getConfiguration() must be of the type string, null given, called in /path/to/your/server/typo3_src/typo3_src-9.5.3/typo3/sysext/rte_ckeditor/Classes/Controller/BrowseLinksController.php on line 149" 

It seems that there is no fieldname set in the getConfiguration function.
Tested with TYPO3 9.5.3

**Comment by mabolek** [comment]
![screenshot_14](https://user-images.githubusercontent.com/8200271/52281566-adbcb180-295e-11e9-9712-ddb27d8e2312.png)
