### ISSUE TITLE
Not possible to edit text in 'Text & Image' CE

### ISSUE THREAD

**Issue by mabolek** [FriendsOfTYPO3/frontend_editing#324]
'Text & Image' content element can't be edited. Editor panel at the top of the page doesn't appear. Only header can be edited.

**Comment by mabolek** [comment]
Google Chrome 71, Windows 10. Text & Media appears to be working correctly.

**Comment by glucka** [comment]
I have the same problem with Chrome 71 (ubuntu) but with Chrome beta 74 works again

**Comment by anjeylink** [comment]
@mabolek Editing of content element fields require template changes for every element where every field need to defined.
`<core:contentEditable table="tt_content" field="subheader" uid="{uid}">
    {subheader}
</core:contentEditable>`

Fluid content elements templates are override in T3kit so this needs to be fixes in t3kit. By default content elements can be edited only with edit icons(in popup window and not as inline element)
