### ISSUE TITLE
New content element can only be added to empty page

### ISSUE THREAD

**Issue by mabolek** [FriendsOfTYPO3/frontend_editing#325]
When the page is empty there is a possibility to add new content elements from the "Tools and properties" bar, but if at least one element is present on the page, the possibility to add another element is blocked.

**Comment by mabolek** [comment]
![image](https://user-images.githubusercontent.com/8200271/52282545-f70e0080-2960-11e9-87f9-6ee8427606bf.png)
![image](https://user-images.githubusercontent.com/8200271/52282565-01c89580-2961-11e9-8f28-836a6e032987.png)

**Comment by Idleworks** [comment]
+1

TYPO3 9.5.5, frontend_editing 1.4.6
on win 10 chrome/firefox

**Comment by andrekoller** [comment]
Same here 9.5.5 and 1.4.6

**Comment by anjeylink** [comment]
@andrekoller @mabolek @Idleworks 
I can reproduce it when admin panet is disabled on FE. 
Working fine after I enable admin panel
![image](https://user-images.githubusercontent.com/11900120/57843356-cdbe0580-77d6-11e9-829a-54b1d8b12d12.png)
