### ISSUE TITLE
Content element can't be deleted

### ISSUE THREAD

**Issue by mabolek** [FriendsOfTYPO3/frontend_editing#327]
The inline actions panel is gone in recent TYPO3 versions.

**Comment by mabolek** [comment]
Compare TYPO3 9.5.4 and 8.7.19

**Comment by mabolek** [comment]
Needs further testing. Possibly related to t3kit v8 for TYPO3 v9 or a single site issue.

**Comment by anjeylink** [comment]
@mabolek "edit icons" won't appear while admin panel is disable. 
It has to be enable using "button" on FE in my case. Maybe in some other cases some TS is require. Anyway this is not a bug in "frontend_editing"
![image](https://user-images.githubusercontent.com/11900120/57839636-c0e9e380-77cf-11e9-93d2-b5843fbd7165.png)

**Comment by anjeylink** [comment]
@mabolek "edit icons" won't appear while admin panel is disable.
It has to be enable using "button" on FE in my case. Maybe in some other cases some TS is require. Anyway this is not a bug in "frontend_editing"

![image](https://user-images.githubusercontent.com/11900120/57839721-e37bfc80-77cf-11e9-8c5d-0248ab77ecb4.png)
