### ISSUE TITLE
2 headings after saving

### ISSUE THREAD

**Issue by benzinkanister** [FriendsOfTYPO3/frontend_editing#330]
After editing and saving a text-element, the heading will be inserted twice.

```
<h2>Test</h2>
<p>Text</p>
```

is saved to:

```
<h2>Test</h2>
<h2>Test</h2>
<p>Text Text</p>
```

In the backend the 2nd heading is placed in the bodytext-area.

**Comment by myroslav321** [comment]
@benzinkanister Can't reproduce this issue, can you pls provide more information?

**Comment by mabolek** [comment]
Possibly related to #304

**Comment by mabolek** [comment]
I'm closing this issue as no further information has been provided by the reporter.
