### ISSUE TITLE
Frontend editing not working with tx_news and page browser

### ISSUE THREAD

**Issue by nannione** [FriendsOfTYPO3/frontend_editing#346]
TYPO3 8.7.26, tx_news 7.2 and frontend_editing latest version: All FE menus disappear in front end as soon I change to the second page of the news list view via page browser.

**Comment by mabolek** [comment]
Hi @nannione!

Thank you for reporting this bug. I'm able to reproduce it here, so we'll look into it.

It seems news is taking with it the `frontend_editing=true` URL parameter into the link. That could be the reason.

**Comment by nannione** [comment]
Hi @mabolek !
Thanks. I confirm it is due to the "frontend_editing=true" part in the url for the followup pages. Manually removing the part resolves the issue.

The detail view of tx_news seems to be affected too. Not really an issue for editing an article since it can be done via the list view:
<img width="1584" alt="Bildschirmfoto 2019-06-19 um 15 33 48" src="https://user-images.githubusercontent.com/7661543/59774801-f9d21800-92a7-11e9-8c29-7111c56d7358.png">
