### ISSUE TITLE
Can not add media by url in Safari

### ISSUE THREAD

**Issue by nannione** [FriendsOfTYPO3/frontend_editing#347]
I can not add a media by url (e.g. YouTube video) .The url field allows to add one character only. TYPO3 version 8.7.25
<img width="1064" alt="Bildschirmfoto 2019-06-16 um 15 57 53" src="https://user-images.githubusercontent.com/7661543/59566032-50461900-9052-11e9-9a63-0abbffccfddc.png">

**Comment by mabolek** [comment]
Hi @nannione! 

Thank you for reporting this. I can confirm the bug is reproducible. We'll look into it.

**Comment by mabolek** [comment]
Reproducible:

- [x] Safari
- [ ] Chrome
- [ ] Firefox (TBD)

**Comment by nannione** [comment]
Not reproducible on FireFox (MacOsX)

**Comment by MattiasNilsson** [comment]
@nannione This have been solved in the latest release which is https://github.com/FriendsOfTYPO3/frontend_editing/releases/tag/1.9.9
