### ISSUE TITLE
Editing panel is gone in TYPO3 v9.5

### ISSUE THREAD

**Issue by mesosa** [FriendsOfTYPO3/frontend_editing#349]
I am using frontend editing v1.5.0 and when clicking a content element, there is no editing panel anymore at the top of the element. 
Appears and works on TYPO3 v8.7.27 but not in TYPO3 v9.5.5

![fe t3 8727](https://user-images.githubusercontent.com/4276194/62038478-1130e900-b1f6-11e9-8787-a60ae0920a88.png)
![fe t3 955](https://user-images.githubusercontent.com/4276194/62038480-142bd980-b1f6-11e9-8342-fdf45196205c.png)

**Comment by mabolek** [comment]
Hi @mesosa!

Thanks for reporting. This has to be implemented throguh a PSR-15 middleware in the same way as it's done in the new feedit extension in TYPO3 v9 LTS.

This functionality was originally implemented using the `$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['typo3/classes/class.frontendedit.php']['edit']` hook. This hook technically still there in v9 (it hasn't been officially deprecated), but it's actually never executed.
