### ISSUE TITLE
Dropzones only appear if adminpanel is activated

### ISSUE THREAD

**Issue by mkrappitz** [FriendsOfTYPO3/frontend_editing#353]
I got EXT:frontend_editing 1.6.0 running on TYPO3 9.5.9 (with EXT:mask and EXT:gridelements) and also EXT:adminpanel installed and running in frontend. Strange behaviour, only if the admin panel in the frontend is switched on (green state), the dropzones for new content elements of EXT:frontend_editing are rendered into the markup. If the admin panel is switched off (red state) the dropzones of EXT:frontend_editing are not rendered into the frontend. I doubt this is desirable behaviour. But if it is, it should at least be documented. This just costed me 4 hours to find out.

**Comment by mabolek** [comment]
Hi @mkrappitz!

Thanks for reporting. We'll have a look at this. It's possibly related to #349

**Comment by fabtho** [comment]
Same here  TYPO3 9.5.9 with 1.6.0. Only if I have adminpanel extension installed editing works.  Even if I set  config.admPanel = 0.
