### ISSUE TITLE
full page reload required to view updated page tree

### ISSUE THREAD

**Issue by viacheslavresultify** [FriendsOfTYPO3/frontend_editing#355]
1. add/edit visibility page in page tree
you need to F5 to see changes.

**Comment by tomashavner** [comment]
The same thing occurs if you create a new page or delete one. Hitting the refresh-button does not help.

**Comment by MattiasNilsson** [comment]
This will be solved with v2 of frontend editing as this is now a backend module which uses the native TYPO3 page tree: https://github.com/FriendsOfTYPO3/frontend_editing/pull/434
