### ISSUE TITLE
Filter tree field does not work in Safari browser

### ISSUE THREAD

**Issue by OlenaBulat** [FriendsOfTYPO3/frontend_editing#356]
Filter tree input does not work on MacOS, Safari. No possibility to type in page number into the field.

**Comment by anjeylink** [comment]
@mabolek most likely this is related to #359

**Comment by MattiasNilsson** [comment]
This will be fixed in frontend editing v2 as it will be using the TYPO3 page tree: https://github.com/FriendsOfTYPO3/frontend_editing/pull/434
