### ISSUE TITLE
Modal with editing form doesn't stop loading

### ISSUE THREAD

**Issue by mabolek** [FriendsOfTYPO3/frontend_editing#363]
![frontend_editor_safari_modal_load_problem](https://user-images.githubusercontent.com/8200271/64406850-29144c00-d083-11e9-87be-795615e1764d.png)

**Comment by jkkauhan** [comment]
I have this same problem. It seems to happen sometimes with other browsers too, like Microsoft Edge and even Chrome. I noticed the problem goes away one time if I clear the browser cache. So I tried disabling client caching within .htaccess and the modal worked fine after that. Could the problem be caused by javascript loading order or timing?

**Comment by mabolek** [comment]
Hi @jkkauhan! That's an interesting discovery. I'll check that.

Thank you for letting us know!

**Comment by boosim** [comment]
Hi @mabolek,
we ran into this issue, too

We experienced this problem mainly in Firefox but we couldn't exactly pinpoint when it happens.
If you use the View Module in the backend it seems to work always, only in Frontend alone the problem occured.

The following error message is visible in the Console only when the problem occurs:

jQuery.Deferred exception: top.TYPO3.Backend.consumerScope is undefined FormEngine.initializeEvents@https://www.beispielurl.de/typo3/sysext/backend/Resources/Public/JavaScript/FormEngine.js?bust=df140cf7e5f7f3c7a40c20368343df94a126a445:605:7 FormEngine.initialize/<@https://www.beispielurl.de/typo3/sysext/backend/Resources/Public/JavaScript/FormEngine.js?bust=df140cf7e5f7f3c7a40c20368343df94a126a445:1612:18 l@https://www.beispielurl.de/typo3temp/assets/compressed/jquery.min-a948aafd204b1e30253f727c77a2ff5b.js:2:29392 a/</c<@https://www.beispielurl.de/typo3temp/assets/compressed/jquery.min-a948aafd204b1e30253f727c77a2ff5b.js:2:29694 undefined jquery.min-a948aafd204b1e30253f727c77a2ff5b.js:2:30947
TypeError: top.TYPO3.Backend.consumerScope is undefinedFormEngine.js:605:7
    initializeEvents https://www.beispielurl.de/typo3/sysext/backend/Resources/Public/JavaScript/FormEngine.js?bust=df140cf7e5f7f3c7a40c20368343df94a126a445:605
    initialize https://www.beispielurl.de/typo3/sysext/backend/Resources/Public/JavaScript/FormEngine.js?bust=df140cf7e5f7f3c7a40c20368343df94a126a445:1612
    jQuery 2
    
    l
    
    c

Thanks for your work!

**Comment by mabolek** [comment]
Hi @boosim!

Thanks for the extra input.

We've had a hard time reproducing the issue, so your debugging info could be what we need.

I'm going to remove the specific reference to Safari.

**Comment by kevinandrewsde** [comment]
I had the same problem under all browsers except for Chrome, coincidentally, the fix that i applied locally to fix #390 for our deployments on, i.e., commenting out a bunch of lines starting at Resources/Public/JavaScript/Editor.js:121 to the following:
```
modalIframe.on('load', function () {
	$.extend(window.TYPO3, modalIframe[0].contentWindow.TYPO3 || {});

	// Simulate BE environment with correct CKEditor instance for RteLinkBrowser
	//top.TYPO3.Backend = top.TYPO3.Backend || {};
	//top.TYPO3.Backend.ContentContainer = {
	//	get: function () {
	//		return modalIframe[0].contentWindow;
	//	}
	//};
});

currentModal.on('hidden.bs.modal', function (e) {
	//delete top.TYPO3.Backend.ContentContainer;
	F.refreshIframe();
});
```
This fixes both #390 and #363 for me. But i am not sure yet, what adverse effects this might have.

**Comment by matin73** [comment]
Bug still exists in TYPO3 10.4.2. Also problems when saving changed content - page overlay and spinning do not remove.

**Comment by matin73** [comment]
kevinandrewsde fix work for me on modal issue. thanks!

**Comment by matin73** [comment]
But problem when saving data still exists.
