### ISSUE TITLE
Attributes rendered in the wrong place

### ISSUE THREAD

**Issue by flack** [FriendsOfTYPO3/frontend_editing#366]
I have an old typo3 site which recently migrated to 9.5 and fluid. Since then, the frontend editing doesn't work right anymore. When I have a text container, both the header and the bodytext are shown as one editable area, and when I save, the header gets saved as bodytext (i.e. duplicated). So basically exactly the same behavior as in #304, but the solution there doesn't seem to apply. Or at least I grepped the entire codebase, and `beforeLastTag` is never set. Or is it something I have to do explicitly? The explanation in #336 is not very clear (also, it doesn't really say whether `0` or `1` is the correct value. Or does it depend on the situation?)

**Comment by mabolek** [comment]
Hi @flack!

Thanks for opening this issue.

Would you be able to post some code examples here? It would help us debug the issue.

**Comment by flack** [comment]
Hi @mabolek! 

Sury, I can post something. What exactly are you looking for? The Fluid template where it happens is the one from typo3 core

**Comment by mabolek** [comment]
@flack, your TypoScript would be the most interesting here. That would make it possible for us to see any problems there or replicate and test it.

**Comment by flack** [comment]
@mabolek hm, ok, I'll give it a try. But like I said it's an old site not written by me orginially, and the person that wrote it is AWOL..

I've looked over all the TS I could find, and only this looked like it could be relevant:

```
page.10 = FLUIDTEMPLATE
page.10 {
  # Set the Template Pathes
  layoutRootPath = fileadmin/resources/templates/layouts/
  variables {
    content < styles.content.get
    level = TEXT
    level.data = level:1
  }
}

# Assign the Template files with the Fluid Backend-Template
page.10.file.stdWrap.cObject = CASE
page.10.file.stdWrap.cObject {
  key.data = levelfield:-1, backend_layout_next_level, slide
  key.override.field = backend_layout

  # Set the default Template, our 3 column Template
  default = TEXT
  default.value = fileadmin/resources/templates/defaultContent.html
}
```

In the template, I have the following includes:

- Fluid Styled Content (fluid_styled_content)
- Fluid Styled Content CSS (optional) (fluid_styled_content)
- Gridelements (gridelements)
- Form (form)

There is also a frontend_editing include available, but for some reason, inline editing works without it, too. If I add it to the list of includes, what happens depends on the order:
- if frontend_editing is before fluid_styled_content, then the behavior is like when it's not in the list at all (image sections get floating toolbars, text sections are inline editable, but have not toolbars)
- if frontend_editing is after fluid_styled_content, then every section gets a floating toolbar, but nothing is inline editable

**Comment by MattiasNilsson** [comment]
@flack Is this still relevant? Are the attributes added correctly in the DOM or is it just visually?

**Comment by flack** [comment]
@MattiasNilsson in the end it turned out the client doesn't really use the frontend editing features anyways, so I never really followed up on the issue. I just checked again in my local instance, and now it seems like it's working, i.e. headline and body are separate fields. So maybe it was fixed by some point release in the last one and a half years? In any case, I guess the ticket can be closed
