### ISSUE TITLE
Hidden Elements-feature only works in some environments in TYPO3 9.5.x

### ISSUE THREAD

**Issue by pxamike** [FriendsOfTYPO3/frontend_editing#367]
Tested with TYPO3 9.5.9 with frontend_editing 1.6.1.

![Selection_427](https://user-images.githubusercontent.com/12510409/66050287-3b23c600-e52d-11e9-99f1-1351f8b99e05.png)
- By clicking "Hidden Elements" icon in the right pane, the hidden elements on the page will be visible. Locally this works for me. But on **platform.sh** the hidden elements are not showing. If I do the following changes, I'm able to see the hidden records when "Hidden Elements" is enabled. 

1. In BE, add **config.admPanel=1** in Typoscript (setup field)
2. In FE, enable the admin panel.
![Selection_430](https://user-images.githubusercontent.com/12510409/66050657-df0d7180-e52d-11e9-8282-a706091ef1a4.png)

3. Edit the settings and enable either "Show hidden pages" or "Show hidden records" and update the settings.
![Selection_431](https://user-images.githubusercontent.com/12510409/66050691-f3ea0500-e52d-11e9-938f-ffb3e66e09fc.png)

The problem using this workaround is that it only works for administrators (and only with the admin panel enabled).

**Comment by mabolek** [comment]
Fixed in 1.8.2

**Comment by iv-litovchenko** [comment]
If the page has disabled "sys_template" with settings and enabled "show hidden records"

$ includeHiddenPages = true;
$ includeHiddenContent = true; ->!
GeneralUtility :: makeInstance (VisibilityAspect :: class, $ includeHiddenPages, $ includeHiddenContent, false)

then the "sys_template" template also applies, which is not needed :)
