### ISSUE TITLE
Custom Content Elements not added to right bar

### ISSUE THREAD

**Issue by afreuler** [FriendsOfTYPO3/frontend_editing#376]
Hi, it seems that custom fluid_content_elements are not added to the right bar. In the backend they are available and everything works fine. In frontend I can edit them but can not add new ones. 

Typo3 9.5.9 
frontend_editing 1.7.0

**Comment by mabolek** [comment]
Hi @afreuler!

This could be because the content elements are added to the wizard within a backend-only condition.

For example, this was an issue with the frontend login form content element. Check out the bug report and fix:
https://forge.typo3.org/issues/88617#change-402278

**Comment by afreuler** [comment]
thanks for your reply @mabolek,

unfortunately this does not fix it.

In frontend_editing/Classes/Hook/FrontendEditingInitializationHook.php on line 702 the content elements are fetched:
```
$contentController = GeneralUtility::makeInstance(NewContentElementController::class);
$wizardItems = $contentController->wizardArray();
```
while in frontend the pid is undefined and only the standard content_elements are loaded from PageTSConfig typo3_src/typo3/sysext/backend/Classes/Controller/ContentElement/NewContentElementController.php 
line 203: 
`$this->id = (int)($parsedBody['id'] ?? $queryParams['id'] ?? 0);`

**Comment by mabolek** [comment]
@afreuler Thank you. We have not experienced an issue with loading other custom content elements (we regularly use custom elements ourselves).

Just to be sure, could you check the load order for frontend_editing and your content elements? Maybe yours are somehow loaded too late?

Would you be able to provide us with the configuration of your custom element so we can compare it to what we're using?

Thank you for your assistance.

**Comment by afreuler** [comment]
Hi, thanks again!

I tried to change the load order but it did not help.
My elements I define in my own basedistribution extension. 
This is my tsconfig for one element (loaded on my root page, On the same page I have my root-template in which I include the fluid_styled_content and frontend_editing static templates and the main template typoscript):

```
mod.wizards.newContentElement.wizardItems.common{
    elements {
        myextension_myelement{
            iconIdentifier = myextension-myelement
            title = Myelement
            description = My fantastic element
            tt_content_defValues {
                CType = myextension_myelement
            }
        }
       show := addToList(myextension_myelement)
} 
```

In typo3conf/ext/myextension/Configuration/TCA/Overrides/pages.php:

```
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::registerPageTSConfigFile(
    'myextension',
    'Configuration/TSconfig/Page/PageConfig.ts',
    'Custom Content Elements'
);
```
in /typo3conf/ext/myextension/Configuration/TCA/Overrides/tt_content.php

```
HelperUtility::addContentElement(
    'Myelement',
    'myextension_myelement',
    'myextension',
    'EXT:myextension/Resources/Public/Icons/ContentElements/myextension-myelement.svg',
    'myextension-myelement'
);
```

In typo3conf/ext/myextension/Classes/Utility/HelperUtility.php

```
<?php

namespace FP\Myextension\Utility;

class HelperUtility
{
    /**
     * Add content element in Configuration/Overrides/tt_content.php
     *
     * @param $title The title of the content element (LLL:...)
     * @param $cType The CType of the content element, e.g. vatemplate_text
     * @param string $extensionKey The extension the content element is stored,
     * @param $iconPath The path to the icon file
     * @param $typeIconClass The typeicon class
     */
    public static function addContentElement($title, $cType, $extensionKey = 'myextension', $iconPath = '', $typeIconClass = '') {
        \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPlugin(
            array(
                $title,
                $cType,
                $iconPath?$iconPath:'EXT:myextension/Resources/Public/Icons/myextension.svg'
            ),
            'CType',
            $extensionKey
        );

        if($typeIconClass === ''){
            $typeIconClass = str_replace('_', '', $extensionKey);
            $typeIconClass = str_replace('-', '', $typeIconClass);
            $typeIconClass = 'ext-' . $typeIconClass . '-content-' . str_replace($typeIconClass . '_', '', $cType) . '-icon';
        }

        $GLOBALS['TCA']['tt_content']['ctrl']['typeicon_classes'][$cType] = $typeIconClass;
    }
}
```

**Comment by afreuler** [comment]
Hi again, 
loading the TsConfig for the Custom Content-Elements in MyExtension/ext_localconf.php
`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPageTSConfig('<INCLUDE_TYPOSCRIPT: source="FILE:EXT: MyExtension/Configuration/TSconfig/Page/PageConfig.ts">');`

instead including it in Page TSConfig (from extensions) (in MyExtension/Configuration/TCA/Overrides/pages.php)
```
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::registerPageTSConfigFile(
    'MyExtension',
    'Configuration/TSconfig/Page/PageConfig.ts',
    'Custom Content Elements'
);

```

helped me!

Cheers
