### ISSUE TITLE
Pages deactivated in the backend will still be displayed

### ISSUE THREAD

**Issue by SchmidtWebmedia** [FriendsOfTYPO3/frontend_editing#380]
I have disabled pages in the backend, but they are still displayed in the frontend menu. As soon as I deactivate the extension frontend_editing, it works as usual and the pages are not displayed. It doesn't matter if I'm logged into TYPO3 backend or not.

Frontend_Editing: 1.8.1

**Comment by mabolek** [comment]
Hi @SchmidtWebmedia!

Thank you for opening the issue. We'll look into this.

To assist our debugging: 
1) Have you tried loading the website in a different browser. 
2) Have you cleared the cache before logging out and reloading the page.

**Comment by SchmidtWebmedia** [comment]
Hi @mabolek , thanks for answer. 

1) yes I've tested Chrome and Firefox = Same result
2) yes I've cleared the chache (TYPO3 and Browser)

The problem has occured since 1.7.0 (At least I've recognized it since then.)

**Comment by OlenaBulat** [comment]
I have the same issue. 
The extension was updated to 1.8.1 version.  
1. In the main navigation menu appears hidden pages; 
2. When I am logged in BE I can see content on that pages (with 'Preview' mark)
3. If I am not logged in BE -> get an error _Page Not Found Reason: ID was not an accessible page_

**Comment by mabolek** [comment]
Thank you for your feedback, @SchmidtWebmedia and @OlenaBulat. There seems to be a caching issue.

PS! Please make sure `[FE][disableNoCacheParameter]` is disabled in your install.

**Comment by birgitrg** [comment]
Same issue here.
[FE][disableNoCacheParameter] = false 
Hidden pages are always visible in menues on FE pages if EXT:frontend_editing ist installed.
Same error message on that FE pages.
It does not matter if EXT is activated or not in TS.
I tried:
TYPO3 9.5.9, 9.5.10, 
EXT:frontend_editing 1.7.0, 1.8.1
