### ISSUE TITLE
Typoscript "spamProtectEmailAddresses" not working with frontend_editing

### ISSUE THREAD

**Issue by erredeco** [FriendsOfTYPO3/frontend_editing#405]
**Steps to reproduce (TYPO3 9.5.13):**

1) add in TS Setup the TypoScript code

```
config{
	spamProtectEmailAddresses = 1
	spamProtectEmailAddresses_atSubst = [at]
}
```
2) Install frontend_editing and add in "Include static (from extensions)": frontend_editing (I included it as last element)
3) Add a text element and add to it an email address. the autocomplete with add the mailto href.
4) Visit the frontend

**Expected results**

The email address should be encrypted

**Current result**
 
The email address is not encrypted

**Additional information**

* the issue is present even if `config.frontend_editing = 0`
* the issue is present even if not logged in TYPO3 (you could test it with a different browser)
* the javascript encrypt function is still present; no javascript error is thrown

**Comment by mabolek** [comment]
@erredeco Thank you for submitting this issue. We'll check this.

This could be related to #403.

**Comment by mabolek** [comment]
@OlenaBulat Do you mind checking this issue as well when you check #403?

**Comment by erredeco** [comment]
I included `frontend_editing` as last item on  `Include static (from extensions)` and both mine issue and #403 are still present.
both issues are not present if I include it as _first item_ but I don't know if it is intended to work that way.

I included it as last as shown on documentation (https://docs.typo3.org/p/friendsoftypo3/frontend-editing/master/en-us/Installation/Index.html)

**Comment by kevinandrewsde** [comment]
Same here, #405 and #403 both work when frontend_editing is included -before- everything else.

**Comment by mabolek** [comment]
@erredeco @kevinandrewsde Do you mind testing pull request #423? I have updated the TypoScript condition to be more restrictive, as well as explicitly setting `config.spamProtectEmailAddresses = 0`.

The template should be included last.

**Comment by mabolek** [comment]
@erredeco @kevinandrewsde Just a reminder to check out pull request #423, which should fix this issue. 😄
