### ISSUE TITLE
Core: Error handler (FE): PHP Warning: DOMDocument::loadHTML():

### ISSUE THREAD

**Issue by k2220** [FriendsOfTYPO3/frontend_editing#408]
Use TYPO3 9.5.13

After editing of a Page and Logout, see only a blank page.
Error log show this error message: 
Core: Error handler (FE): PHP Warning: DOMDocument::loadHTML(): Empty string supplied as input in /....../typo3conf/ext/frontend_editing/Classes/Hook/FrontendEditingInitializationHook.php line 172

**Comment by kevinandrewsde** [comment]
Duplicate of #402
