### ISSUE TITLE
Highlight of "Save all" button missing for editors

### ISSUE THREAD

**Issue by cdaecke** [FriendsOfTYPO3/frontend_editing#414]
As soon as I change content in the frontend as a admin, the `Save all` button get's  highlighted:

<img width="455" alt="admin" src="https://user-images.githubusercontent.com/2102444/78653894-10dc0800-78c4-11ea-8ea7-b2e0b4b8ea7d.png">

This feature is missing for "normal" editors:

<img width="455" alt="editor" src="https://user-images.githubusercontent.com/2102444/78653963-27825f00-78c4-11ea-9140-b51b1d14a14e.png">

It would be nice, if editors would have this feature as well.

**Comment by mabolek** [comment]
Hi @cdaecke!

I have been testing this in Frontend Editing on TYPO3 versions 10.4 and 9.5 today, and I'm unable to reproduce this issue. 

Do you see any errors in the browser console?

In what browser and TYPO3 version do you have this issue?

**Comment by cdaecke** [comment]
@mabolek I have just updated the extension from version 1.9.2 to 1.9.3 and now it seems to work. Thanks for your investigation!

I close this issue.

**Comment by mabolek** [comment]
Thank you for the feedback, @cdaecke.
