### ISSUE TITLE
Editing existing records for tx_news

### ISSUE THREAD

**Issue by agendartobias** [FriendsOfTYPO3/frontend_editing#415]
Hey, any idea how can i configure frontend_editing so i will be able to edit existing records for news?

For adding new news record i used <core:customDropZone in template and it works great. When i drop the element new popup window appears for add news record.

But if i go to single news record view i cannot edit the record. I tried to use <core:contentEditable but it's not ok. I will prefere popup window to edit all fields. It this a bug or am i doing something wrong?

**Comment by mabolek** [comment]
Hi @agendartobias! 

I haven't done a news integration like that myself, but you have to make sure that Frontend Editing knows which record is being displayed in the single view. By default it will only edit the plugin content element.

**Comment by MattiasNilsson** [comment]
@agendartobias Do you have any code examples on how you have done it?

**Comment by MattiasNilsson** [comment]
@agendartobias You can now find a fully working example here as a gist: https://docs.typo3.org/p/friendsoftypo3/frontend-editing/master/en-us/InlineEditing/Index.html#contenteditable
