### ISSUE TITLE
doesn't stop loading after saving changes.

### ISSUE THREAD

**Issue by matin73** [FriendsOfTYPO3/frontend_editing#419]
I have issue in TYPO3 10.4.1 after trying to save changes - doesn't stop loading after saving changes and t3-frontend-editing__loading-screen does not get hidden

**Comment by MattiasNilsson** [comment]
@matin73 Can you provide if you get any Javascript errors in the browser inspector? Which browser are you using?

**Comment by matin73** [comment]
There are no JS errors in console.

**Comment by matin73** [comment]
Firefox an Chrome tested - same problem

**Comment by mabolek** [comment]
I am able to reproduce this in TYPO3 10.4.2. Looking into it.
