### ISSUE TITLE
Fix CKEditor base path

### ISSUE THREAD

**Issue by mabolek** [FriendsOfTYPO3/frontend_editing#426]
Set `window.CKEDITOR_BASEPATH = $domainName` as @jan-vodila suggests in a reply to issue #377

**Comment by vaxul** [comment]
Hi @mabolek,

do I read it right, that this is an existing issue?

I get the following result...
`window.CKEDITOR_BASEPATH = 'typo3\/sysext\/rte_ckeditor\/Resources\/Public\/JavaScript\/Contrib\/';`

... for the result of:
https://github.com/FriendsOfTYPO3/frontend_editing/blob/2.0.1/Classes/Hook/FrontendEditingInitializationHook.php#L383-L387

Which results in wrong JS resource paths:
![image](https://user-images.githubusercontent.com/3798226/115671897-47f44e80-a34b-11eb-947b-d876112d438b.png)

And a JS error:
![image](https://user-images.githubusercontent.com/3798226/115672011-64908680-a34b-11eb-809c-b794d0eafe78.png)

Wouldn't it a solution to just use an absolute path instead?

**Comment by MattiasNilsson** [comment]
Fixed with #531
