### ISSUE TITLE
frontend_editing 2.0 iframe doesn't reload after modal edit

### ISSUE THREAD

**Issue by webian** [FriendsOfTYPO3/frontend_editing#441]
Step to reproduce:
1. have frontend_editing 2.0 (not sure if this problem was present also in < 2.0)
2. click the edit pencil of a page content or record
3. edit > save > close

Expected behavior: iframe reloads to display the changes
Actual behavior: iframe doesn't reload

**Comment by webian** [comment]
PR incoming that fixes this

**Comment by MattiasNilsson** [comment]
Fixed in: 442
