### ISSUE TITLE
Loading doesn't finish

### ISSUE THREAD

**Issue by okroener** [FriendsOfTYPO3/frontend_editing#454]
![fe_edit_loading](https://user-images.githubusercontent.com/4545439/102459318-bcd61580-4045-11eb-9fb2-7ee3733130dd.PNG)

There seems to be an issue with frontend editing.

This only applies to specific pages, some do load properly.

Does anyone experience the same behaviour?

**Comment by MattiasNilsson** [comment]
@okroener In which version is this? Can you se what kind of pages it affects?

**Comment by okroener** [comment]
@MattiasNilsson it's version 1.9.5 and trying to figure out what the issue is about.

An exception comes up, with stickyHeader but that seems to belong to the boostrap_package.

Are there any known issues when using bootstrap_package?
