### ISSUE TITLE
After saving double Headlines

### ISSUE THREAD

**Issue by quadronet** [FriendsOfTYPO3/frontend_editing#476]
Hello, when I edit a content item and then save it, the heading from the ce-element is duplicated. Again and again, save three times = 3 headings. What could that be?
The double heading are after saving in the Texteditor.

**Comment by MattiasNilsson** [comment]
@quadronet Thanks for your feedback we look into it! To make the debugging a bit easier do you have some more examples that we can take a part of?

**Comment by Messj1** [comment]
@quadronet Your problem sounds familiar to me :godmode:
What is the value of `tt_content.text.stdWrap.editIcons.beforeLastTag` if you have look in typoscript Object Browser?

If the value is set to 1, which is the default, the whole content will be wrap as an editable field.
https://github.com/FriendsOfTYPO3/frontend_editing/blob/master/Classes/EditingPanel/FrontendEditingPanel.php#L107

If you set the value of `tt_content.text.stdWrap.editIcons.beforeLastTag` to 0, the content will be wrapped with an inline action field (new, move, delete, update).
Hint: to wrap each content (bodytext and header) with an editable field you have to adapt the fluid CE templates or load an adapted version of the default templates which is already delivered within this extension. ("editable fluid styled content v9")

**Comment by MattiasNilsson** [comment]
@quadronet as @Messj1 states this can be solved either by the Typoscript setting `tt_content.text.stdWrap.editIcons.beforeLastTag` or by using the ts include **"editable fluid styled content v9"**. It all depends on your content element type.

So this is being closed.
