### ISSUE TITLE
HTMLparser changes break cHash validity for EXT:form when Frontend Editing is disabled

### ISSUE THREAD

**Issue by lorenzulrich** [FriendsOfTYPO3/frontend_editing#477]
The `HTMLparser` code at https://github.com/FriendsOfTYPO3/frontend_editing/blob/d2a714ab55a0e68a1be8d6a8d295707024563128/Configuration/TypoScript/setup.ts#L86 is added for condition `[backend.user.isLoggedIn]`, i.e. whenever a backend user is authenticated - even if frontend editing is disabled.

Since this "fixes" the action of a form `action` attribute, it will always append `?frontend_editing=true` to any form in the content, also forms from EXT:form. Since this is an argument that is not taken into account when calculating the cHash of the form, it will break the form submission with the following error:

> Page Not Found
> The page did not exist or was inaccessible. Reason: Request parameters could not be validated (&cHash comparison failed)

From reading the [commit that introduced this code](https://github.com/FriendsOfTYPO3/frontend_editing/commit/032c18a9abcc6c8c95138527fd29ad65f7182ebf), I don't understand what the intention is (or what . But I assume it was not meant to target forms in content elements?

## How to reproduce?

* Install and configure EXT:frontend_editing, but don't activate it for the current user.
* Install EXT:form and setup a form as content (or alternatively: use an Extbase extension rendering a form with a Fluid-generated form POST action).
* Visit the page with the form in frontend while being authenticated as backend user.
* In the source code, you will see that the form action was appended with `frontend_editing=true`:

![image](https://user-images.githubusercontent.com/1816023/107815985-67339600-6d74-11eb-9329-25b3b25a89e2.png)

* Try submitting the form. You will get the following error:

![image](https://user-images.githubusercontent.com/1816023/107816058-76b2df00-6d74-11eb-822c-409c4810e6ac.png)

## Workaround

Deactivate the `fixAttrib` for the form tag:

```
[backend.user.isLoggedIn]
  config.tx_frontendediting.pageContentPreProcessing.HTMLparser.tags.form.fixAttrib >
[GLOBAL]
```

However, this must have some drawbacks?

**Comment by mabolek** [comment]
Hi @lorenzulrich!

Thank you for submitting this issue.

Which version of frontend_editing and TYPO3 are you using?

I think the solution would be to change the TypoScript condition `[backend.user.isLoggedIn]` to  
`[backend.user.isLoggedIn && request.getQueryParams()['frontend_editing'] == true]`.

PS! The reason for adding `frontend_editing=true` to the form URL is that some sites require a form submit to access certain editable data, but also that (accidentally) submitting any form with frontend editing enabled will lead to an inception (the editor's wrapper output being loaded within itself).

**Comment by MattiasNilsson** [comment]
@lorenzulrich I have made a Pull Request that solves this. Can you verify if it works for you? https://github.com/FriendsOfTYPO3/frontend_editing/pull/478
