### ISSUE TITLE
disallow_backend_access: Error: Could not fetch editor configuration due to  a request error

### ISSUE THREAD

**Issue by max951** [FriendsOfTYPO3/frontend_editing#480]
Frontend editing works very well if backend access is allowed.
but if I set "frontend_editing.disallow_backend_access = 1"
the following message appears after logging in
![hc_597](https://user-images.githubusercontent.com/12292845/108524033-e5d98780-72ce-11eb-9705-382331b02f83.png)

TYPO3 10.4.13 / frontend_editing 1.9.8

**Comment by MattiasNilsson** [comment]
@max951 A Pull Request have been made, can you verify it? https://github.com/FriendsOfTYPO3/frontend_editing/pull/482

**Comment by max951** [comment]
After the fix #482 the error has gone and the login works fine.
Thanks for the quick reply.
