### ISSUE TITLE
Deprecation notices for v11

### ISSUE THREAD

**Issue by hacksch** [FriendsOfTYPO3/frontend_editing#483]
Hello,
i noticed a deprecation notice under TYPO3 10.4.13.

1.  For the usage of $GLOBALS['TSFE']->fePreview in /Classes/Hook/FrontendEditingInitializationHook.php.

[NOTICE] request="e63e5e7fa252f" component="TYPO3.CMS.deprecations": Core: Error handler (FE): TYPO3 Deprecation Notice: Property $TSFE->fePreview is not in use anymore as this information is now stored within the FrontendPreview aspect. in /var/www/htdocs/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php line 4124 

2. Usage of $TYPO3_CONF_VARS[SC_OPTIONS][tslib/class.tslib_fe.php][contentPostProc-output] hook in /ext_localconf.php

[NOTICE] request="6d6bc2f24675b" component="TYPO3.CMS.deprecations": Core: Error handler (FE): TYPO3 Deprecation Notice: The hook $TYPO3_CONF_VARS[SC_OPTIONS][tslib/class.tslib_fe.php][contentPostProc-output] will be removed in TYPO3 v11.0. Use a custom PSR-15 middleware instead. in /var/www/htdocs/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php line 3267 

3. Usage of hook $TYPO3_CONF_VARS[SC_OPTIONS][tslib/class.tslib_content.php][cObjTypeAndClass] in /ext_localconf.php

[NOTICE] request="8dcda262386e2" component="TYPO3.CMS.deprecations": Core: Error handler (FE): TYPO3 Deprecation Notice: The hook $TYPO3_CONF_VARS[SC_OPTIONS][tslib/class.tslib_content.php][cObjTypeAndClass] for adding custom cObjects will be removed in TYPO3 v11.0. Use a custom cObject which you can register directly instead. in /var/www/htdocs/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php line 565

**Comment by MattiasNilsson** [comment]
@hacksch Thanks for reporting this issue. We will have it fixed for when we have verified that frontend editing is fully compatible with TYPO3 11.

**Comment by sheydin** [comment]
Do you have any estimation on when frontend editing will be compatible with TYPO3 11? Thank you.

**Comment by mabolek** [comment]
@sheydin That depends a bit on contributions and schedule, but I know I am going to start looking at it in September.

**Comment by MattiasNilsson** [comment]
Fixed with this PR: https://github.com/FriendsOfTYPO3/frontend_editing/pull/556
