### ISSUE TITLE
Rename typoscript file extensions

### ISSUE THREAD

**Issue by Messj1** [FriendsOfTYPO3/frontend_editing#487]
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/CodingGuidelines/CglTypoScript/Index.html
> TypoScript Coding Guidelines
Directory and File Names
> - As of TYPO3 8.7, the file ending can and should be .typoscript.

Since this project only supports Typo3 >= 8.7 we should change file extension.

`.ts` is widely used by typescript. So to prevent name conflicts it is better to change.
Maybe this project use typescript in 2.0 :upside_down_face:

**Comment by MattiasNilsson** [comment]
@Messj1 Great feedback and we are already on it. If you take a look at the develop-2.0 branch which will be version 2.0, You can find that this have already been done :)

https://github.com/FriendsOfTYPO3/frontend_editing/tree/develop-2.0/Configuration/TypoScript
