### ISSUE TITLE
integrate loadingscreen, modal and notification module

### ISSUE THREAD

**Issue by Messj1** [FriendsOfTYPO3/frontend_editing#495]
Integrate the new modules developed in #467

* `TYPO3/CMS/FrontendEditing/LoadingScreen`
* `TYPO3/CMS/FrontendEditing/Notification`
* `TYPO3/CMS/FrontendEditing/Modal`

ToDo:
- [x] deprectade methodes:  `F.confirm`, `F.showSuccess`, `F.showError` and `F.showWarning`
- [x] replace internal calls with equivalent method call
- [x] integrate scrollarea in template and css
- [x] add changed modal styles to fix some broken rules as temporarily solution.

@MattiasNilsson Why was the `.btn` class style globaly changed in `_buttons.scss`?

**Comment by MattiasNilsson** [comment]
@Messj1 It was due to a minor visual bug in the Modals footer buttons. But you can fix it if you like 👍

**Comment by Messj1** [comment]
@MattiasNilsson what logger framework do you think we should use?

I was able to reduce to following selection:

- ulog (https://github.com/download/ulog)
There is an abstraction (`anylogger`) of this project compatible with other logging frameworks. Nice feature: it is build as a bunch of mods/plugins. So yes it is extendable.

- winston (https://github.com/winstonjs/winston)
Nice project with lot of good ideas and handlings. But the maintainer seems to be lost since the issue tracker is running hot and PR aren't merged since september 2002. :thinking:

Initial goal is to log an deprecation warning message and replace that online error function in `FrontendEditing`

**Comment by MattiasNilsson** [comment]
@Messj1 I think both are fine but would suggest to use this one instead: https://github.com/pinojs/pino
