### ISSUE TITLE
logger framework

### ISSUE THREAD

**Issue by Messj1** [FriendsOfTYPO3/frontend_editing#498]
- [x] choice logger framework
- [x] integrate framework
- [x] replace F.error calls
- [x] log warnings
- [x] add info logs
- [x] add debug logs

## Background

> - ulog (https://github.com/download/ulog)
> There is an abstraction (`anylogger`) of this project compatible with other logging frameworks. Nice feature: it is build as a bunch of mods/plugins. So yes it is extendable.
> 
> ...
> 
> Initial goal is to log an deprecation warning message and replace that online error function in `FrontendEditing`

_Originally posted by @Messj1 in https://github.com/FriendsOfTYPO3/frontend_editing/issues/495#issuecomment-790190440_

> I think both are fine but would suggest to use this one instead: https://github.com/pinojs/pino

_Originally posted by @MattiasNilsson in https://github.com/FriendsOfTYPO3/frontend_editing/issues/495#issuecomment-790434875_

## Goal

Using the good old `console` is not a good solution since it is restricted to ... console :upside_down_face:

- tracing the whole function calls during testing (developer, dev-ops, operator)
- fetch more information in production if necessary (operator)
- persist logging information (operator, user)

### Requirements

- `caller` should be shown as event source in `console` instead of logger :exclamation:
- easy configuration, fast and granular
- easy persisting, client side (storage) or sending to server
- small footprint since it is not rocket science
- extendable would be nice

## Candidates

- ulog (https://github.com/download/ulog)
Small [16.7 KiB] javascript logger
- pino (https://github.com/pinojs/pino)
Small [7.1 KiB] node.js logger

Both are not directly compatible with AMD. So I have bundled them.

@MattiasNilsson  Why do you suggest `pino`, it is for node.js written and has a smaller browser handling?

**Comment by Messj1** [comment]
@MattiasNilsson I have made some simple code playground, can you have a look at it.
For me `ulog` looks better at the moment ... :raised_eyebrow:

What do I wrong with `pino`?

https://github.com/Messj1/frontend_editing/tree/498-logger-framework

**Comment by MattiasNilsson** [comment]
@Messj1 I will not constrain you at all! So go ahead with `ulog` and prove that I am wrong! So go with that :)

**Comment by Messj1** [comment]
@MattiasNilsson I added https://github.com/dfahlander/Dexie.js as `IndexedDB` wrapper to get some simple powerful persist feature. Think it can be used later as storage of changed data.
Nothing against `localStorage`. It is nice and easy to use. A truley simple store for simple data like settings or temporary data if you don't like `sessionStorage`. But nothing for complex unflat data.

What do you think about following implementation:
https://github.com/Messj1/frontend_editing/blob/498-logger-framework/Resources/Public/JavaScript/Utils/Logger.js#L26

I am not fully convinced about the implementation. I have this feeling that I missed something :thinking:
Can you please have a look on it?

Can you also check the channel i planed?
https://github.com/Messj1/frontend_editing/blob/498-logger-framework/Resources/Public/JavaScript/Utils/Logger.js#L101
You are able to define a second log level to only persist high level logs like errors. And yes it is fully configurable like the other `ulog` parts too. So you are able to do the opposite since it is only a name (use output to send to server and log only high level logs) :upside_down_face:

Will finish this issue next month since I get busy for the rest of this month. :slightly_frowning_face:

**Comment by MattiasNilsson** [comment]
@Messj1 This is just awesome, I can just add keep up the good work and let me know if you need any more input. This is just pure joy :)
