### ISSUE TITLE
How to enable editing of tx_news?

### ISSUE THREAD

**Issue by klodeckl** [FriendsOfTYPO3/frontend_editing#500]
Hello,

I haven’t found anything how to enable frontend editing for ext tx_news (I don’t want inline editing, I just want the button to edit a news record). Can anybody please give me a hint? Thanks!

**Comment by MattiasNilsson** [comment]
For sure! Could you just elaborate what exactly it is just want? @klodeckl

**Comment by klodeckl** [comment]
I would like an edit button to click for editing the whole news record (not inline editing of a part of the news). The same like it is possible with regular content elements. The same was possible with ext feedit in the past (since fsc the stdwrap viewhelper was needed: https://github.com/georgringer/stdwrapvh).

**Comment by MattiasNilsson** [comment]
@klodeckl A new release which fixes this have been released! Take a look at the release notes:

https://github.com/FriendsOfTYPO3/frontend_editing/releases/tag/1.10.0
