### ISSUE TITLE
Responsive preview bar should affect page content only

### ISSUE THREAD

**Issue by mabolek** [FriendsOfTYPO3/frontend_editing#512]
The responsive preview bar is currently also affecting the size of the UI items. This makes the UI hard to use. It should be moved down to only affect the size of the iframe containing the page content.

![image](https://user-images.githubusercontent.com/8200271/112501504-9680ee00-8d89-11eb-9576-fc81daf4fdf6.png)

**Comment by MattiasNilsson** [comment]
This is fixed with: https://github.com/FriendsOfTYPO3/frontend_editing/commit/0daefd0f9624fa68a258d52d66bd4b9ef516829d
