### ISSUE TITLE
Feature switch to make the formatting bar a popup

### ISSUE THREAD

**Issue by mabolek** [FriendsOfTYPO3/frontend_editing#513]
Make it possible to turn on a feature that uses the CKEditor's default formatting popup (placed just above the edited content), rather than using space for a bar that steals space in the UI.

![image](https://user-images.githubusercontent.com/8200271/112502674-8ddce780-8d8a-11eb-9dd9-45afef585560.png)

**Comment by webian** [comment]
@mabolek is this still wanted after the UI improvements that I made?
