### ISSUE TITLE
Version 1.10.0 is not typo3 9 compatible

### ISSUE THREAD

**Issue by tomashavner** [FriendsOfTYPO3/frontend_editing#516]
In typo3 9 it Throws an error Call to undefined method TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::getPageArguments(). Reason TypoScriptFrontendController::getPageArguments() is only available in typo3 10.

Kind regards

Tomas

**Comment by MattiasNilsson** [comment]
@tomashavner The problem is fixed with the new release: https://github.com/FriendsOfTYPO3/frontend_editing/releases/tag/1.10.1
