### ISSUE TITLE
customRecords: An argument "key" or "id" has to be provided

### ISSUE THREAD

**Issue by cdaecke** [FriendsOfTYPO3/frontend_editing#533]
As soon as I add the following TypoScript configuration for `customRecords` and hit `Frontend editing` in the left bar of TYPO3, I get an error:

    config {
      tx_frontendediting {
        customRecords {
          tx_news_domain_model_news {
            pid = 6
          }
        }
      }
    }

Error:

> #1351584844 TYPO3Fluid\Fluid\Core\ViewHelper\Exception
> An argument "key" or "id" has to be provided in .../typo3_src-10.4.12/typo3/sysext/fluid/Classes/ViewHelpers/TranslateViewHelper.php line 142

TYPO3 10.4.12 or TYPO3 9.5.19
ext:frontend_editing: 2.0.2

Am I missing something?

**Comment by MattiasNilsson** [comment]
@cdaecke This is now fixed with this release: https://github.com/FriendsOfTYPO3/frontend_editing/releases/tag/2.0.3
