### ISSUE TITLE
Can' edit DCE element

### ISSUE THREAD

**Issue by unaiAlambre** [FriendsOfTYPO3/frontend_editing#535]
Some months ago I started using Fronted Editor with DCE wrapping template with

`<core:contentEditable table="tt_content" uid="{contentObject.uid}">`

In Typo3 9 and FE 1.9 and worked really welll.
Now with Typo3 10 and FE 2.0.3 when I wrap DCE elements this way I get this error:

_Oops, an error occurred!
Argument 2 passed to TYPO3\CMS\FrontendEditing\Service\ContentEditableWrapperService::wrapContentToBeEditable() must be of the type string, null given, called in /Users/unai/webserver/ytj2021/typo3conf/ext/frontend_editing/Classes/ViewHelpers/ContentEditableViewHelper.php on line 153_

When of set field parameter there is no error, but cannot edit the DCE in a Popup.
Where don't set the parameter there is the error.

Is like field parameter is needed but in the reference is said: “There is also a possibility to make the content element editable through the popup backend editor. It is done by skipping the field option in the view helper:”

Tried with enablePlaceholders on and off.

**Comment by MattiasNilsson** [comment]
@unaiAlambre A new release is now out that fixes the issue: https://github.com/FriendsOfTYPO3/frontend_editing/releases/tag/2.0.4
