### ISSUE TITLE
Missing first dropzone for new pages

### ISSUE THREAD

**Issue by vaxul** [FriendsOfTYPO3/frontend_editing#536]
### What happen
If I add a new page and try to drag'n'drop a new content element, no dropzone appears.

### What I accept
I would expect that at least a single dropzone is available to add the first content.

**Comment by gordon81** [comment]
I have the same issues, i have solve it  with : `<f:if condition="{content}">
                <f:then>
                    <f:format.html parseFuncTSPath="">{content}</f:format.html>
                </f:then>
                <f:else>
                    <f:if condition="{core:isFrontendEditingActive()}">
                        <f:cObject typoscriptObjectPath="lib.dynamicContent" data="{pageUid: placeholderId, colPos: '0', wrap: '<div class=\"placeholder\">Content |</div>'}" />
                    </f:if>
                </f:else>
            </f:if>`
content variabel is deviniert in TYPOScript styles.content.get .
It work but is not nice.

**Comment by lorenzulrich** [comment]
Is this still the correct solution for the issue?

**Comment by webian** [comment]
I add that the same problem exists in nested content elements.
If a column doesn't have a CE then there's no drop zone to drop a new or existing CE.

**Comment by webian** [comment]
I made this PR https://github.com/FriendsOfTYPO3/frontend_editing/pull/691 to handle this issue.
Please read the [specific documentation](https://github.com/webian/frontend_editing/blob/FEATURE_Drop_zones_for_empty_colums/Documentation/ConfigureAndExtend/EmptyColumns/Index.rst) and give feedback.
