### ISSUE TITLE
TYPO3 v11 Compatibility

### ISSUE THREAD

**Issue by sheydin** [FriendsOfTYPO3/frontend_editing#540]
Hi, thanks for the great work. 

I wonder if there any efforts to get frontend_editing going on TYPO3 v11. Is there any roadmap?

**Comment by mabolek** [comment]
Hi @sheydin! We have no roadmap per se, but support for v11 will definitely be coming.

**Comment by sheydin** [comment]
Hi @mabolek, thanks for the instant reply!
