### ISSUE TITLE
No @2x image rendering by default

### ISSUE THREAD

**Issue by sheydin** [FriendsOfTYPO3/frontend_editing#541]
Images are not rendered in sufficient resolution on retina displays by default. However, the setting is given here: https://docs.typo3.org/p/bk2k/bootstrap-package/master/en-us/Configuration/ImageRendering/Index.html

```
lib.contentElement.settings.responsiveimages.variants {
    default {
        sizes {
            1\.5x {
                multiplier = 1.5
            }
            2x {
                multiplier = 2
            }
        }
    }
}
```

Would be nice to have those settings be defaults in the future.

Thank you.

**Comment by mabolek** [comment]
Hi @sheydin! This doesn't look like an issue with Frontend Editing. It looks like it's related to the Bootstrap Package extension. Try opening an issue there instead: https://github.com/benjaminkott/bootstrap_package/issues/new/choose
