### ISSUE TITLE
Edit Icon Images  Version 2.0.6  / TYPO3 10.4.19

### ISSUE THREAD

**Issue by tomleiter** [FriendsOfTYPO3/frontend_editing#544]
Thanks for fixing Bug #543

But now the Icons Images "escaped". 
Version 2.0.6 
TYPO3 10.4.19

I tested also with parseFunc.htmlSanitize = 0 but it it doesn't work.

![Bildschirmfoto 2021-08-11 um 13 42 11](https://user-images.githubusercontent.com/1402628/129023070-8c99504d-15c0-469a-a2c8-f9251d5cddd7.png)

and the donation link doesn't work  also

**Comment by mabolek** [comment]
Hi @tomleiter!

Thanks for alerting us about the donation link. We don't try it so often ourselves. I'll get that fixed.

As for the edit icon issue, I'm unable to reproduce that locally. Do you have any other extensions installed that could affect these?

**Comment by tomleiter** [comment]
just "mask" ... maybe i can find the bug by my self...

**Comment by mabolek** [comment]
@tomleiter If you send me the HTML code around where you have this issue, I might be able to point you in the right direction.

**Comment by tomleiter** [comment]
the svg icons is rendering in "HTML entities"..       t3-frontend-editing__inline-actions

<span class="icon-markup"> &lt;svg class="icon-color" role="img"&gt;&lt;use xlink:href="/typo3/sysext/core/Resources/Public/Icons/T3Icons/sprites/actions.svg#actions-toggle-on" xmlns:xlink="http://www.w3.org/1999/xlink" /&gt;&lt;/svg&gt; </span>

**Comment by mabolek** [comment]
@tomleiter Thank you for the extra information. This looks strange. As far as I know the edit icons aren't themselves passed through stdWrap. But maybe they are. I'll see if I come up with something.

PS! The donate link has been updated: https://www.paypal.com/donate/?hosted_button_id=B7YZKNCHTYHRW

**Comment by tomleiter** [comment]
Hi Thx... I have the same Problem with the sysext: form.. The Plugin in rendering HTML Code in the Frontend. Maybe thats a Problem with the new 10.4.19 -> https://github.com/typo3/typo3/commit/5a9f592733

**Comment by mabolek** [comment]
@tomleiter Wondering if this article could be of help to you: https://github.com/TYPO3/html-sanitizer/issues/23

**Comment by tomleiter** [comment]
thanks. with the new version of typo3 10.4.20 & Frondtend Editing Version 2.0.6 works all normally again .
