### ISSUE TITLE
I don´t understand this

### ISSUE THREAD

**Issue by quadronet** [FriendsOfTYPO3/frontend_editing#545]
Hey, i have an TYPO3 10.4.19 with the newest frontend_editing, but i can´t edit the code, because i see only html tags in editor. 
![image](https://user-images.githubusercontent.com/3660985/129027381-f10cd592-a6f2-4b64-a24f-d184da198c15.png)

what could that be?

**Comment by tomleiter** [comment]
Fixed in Version  2.0.6 #543

**Comment by mabolek** [comment]
Hi!

1. It looks like you are running Frontend Editing v1. Please upgrade to v2.
2. We just released Frontend Editing v2.0.6, which fixes this issue: https://github.com/FriendsOfTYPO3/frontend_editing/releases/tag/2.0.6
