### ISSUE TITLE
Editing does not work across domains

### ISSUE THREAD

**Issue by mabolek** [FriendsOfTYPO3/frontend_editing#547]
When working on multi-domain TYPO3 instances, you cannot edit pages outside of the domain you are logged in on. Error in browser:

> Refused to display 'https://www.example.com' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

There is currently no error message for the user. This should be implemented.

We should also implement a solution that loads the page through a proxy or directly through TYPO3, so we avoid this error. (There are certain security risks with this, so it must be done very carefully.)

**Comment by klodeckl** [comment]
This is not a bug. A login only works on the logged in domain, on a different domain you have to login again.

**Comment by mabolek** [comment]
Well, if it's not a bug, it's a missing feature. ;-) 

I think we should at least give the user some kind of feedback.

Since you can edit content on any domain though other backend modules, I think the long-term goal should still be to make it possible in Frontend Editing too.

**Comment by olinox14** [comment]
Our Typo3 instance hosts many websites, most are a subdomain of our company's domain, but some have their own domain.
Each website's admin / editors access their websites from their own domain / subdomain, so no problem for them with fe_editing.

However, when a superadmin, who is accessing the BE page tree trough some "admin.domain.net" url, select some website's page, the domain does not match.
The fe_editing module stay stuck at loading, without any explicit error.

This happens even if the target website is a different subdomain of the same domain. Eg: When trying to edit a page of website.domain.net from admin.domain.net

**Comment by MattiasNilsson** [comment]
@olinox14 Sure I totally understand the problem you are facing and we would like to fix it! As always this will take some time to implement and any kind contribution are welcome! So if you are interested to sponsor this feature you can do it here: https://www.paypal.com/donate/?hosted_button_id=B7YZKNCHTYHRW

**Comment by olinox14** [comment]
No problem, it was just to share our usecase with this issue in particular, no hurry here.

**Comment by MattiasNilsson** [comment]
@olinox14 Great and we will see when this can be implemented in the near future.
