### ISSUE TITLE
[Bug] FrontendEditingInitializationHook::getPluginConfiguration must return array

### ISSUE THREAD

**Issue by typoniels** [FriendsOfTYPO3/frontend_editing#563]
In the backend, when I call the module with a random page whose content is output by a plugin, I get the following error message. The frontend editing is no longer functional here.

```
Oops, an error occurred!
Return value of TYPO3\CMS\FrontendEditing\Hook\FrontendEditingInitializationHook::getPluginConfiguration() must be of the type array, null returned
```

TYPO3: v11.5.3
EXT: 3.0.3

![Bildschirmfoto 2021-12-03 um 17 14 37](https://user-images.githubusercontent.com/53429393/144635659-0f68d160-bb94-4a7e-a90f-e625da61144b.jpg)

**Comment by MattiasNilsson** [comment]
@typoniels The issue have been solved and released https://github.com/FriendsOfTYPO3/frontend_editing/releases/tag/3.0.4
