### ISSUE TITLE
Crash page when rendering text contents with empty body [still occurs]

### ISSUE THREAD

**Issue by olinox14** [FriendsOfTYPO3/frontend_editing#567]
I'm sorry, but the bug signaled in the issue #554  issue still occurs:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 1 passed to TYPO3\CMS\FrontendEditing\ViewHelpers\ContentEditableViewHelper::renderAsTag() must be of the type string, null given, called in /var/www/typo3/public/typo3conf/ext/frontend_editing/Classes/ViewHelpers/ContentEditableViewHelper.php on line 108 | TypeError thrown in file /var/www/typo3/public/typo3conf/ext/frontend_editing/Classes/ViewHelpers/ContentEditableViewHelper.php in line 180.`

My extension is in version 2.0.9, and Typo3 is in 10.4.21

**Comment by olinox14** [comment]
The strange part is that even if the error is still logged for some of the websites we hosts, I can not reproduce it...

**Comment by MattiasNilsson** [comment]
@olinox14 Ok I have a hard time to reproduce this one also. Do you use the same TYPO3 and PHP version locally? Which template engine are you using?

**Comment by hacksch** [comment]
@MattiasNilsson 
I had this error too and found the reason. In a special case i had a empty tag.
`<core:contentEditable table="tt_content" uid="{uid}"></core:contentEditable>`
In this case $content in the viewHelper is not a string any more. When you add a space it works without any error.

**Comment by olinox14** [comment]
@MattiasNilsson Yeah, my local env is the very same that the production env, same versions of php and typo3.

All of my templates are built with Fluid (+Flux and VHS)

**Comment by olinox14** [comment]
The very strange part is that this error seems to resolve by itself...
I had this error again logged this morning: `Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 1 passed to TYPO3\CMS\FrontendEditing\ViewHelpers\ContentEditableViewHelper::renderAsTag() must be of the type string, null given, ... `

When I check the page, there are indeed two contents with `null` content on this page.

But when I request this page, no problem: the page displays, no error logged... Why was an error logged 2 hours ago, and not now?

Could this be caused by some code of the previous version of fe_editing that would be cached somewhere? Through I flushed all of the typo3 caches when I updgraded fe_editing to its latest version...

**Comment by MattiasNilsson** [comment]
Thanks all for the nice feedback! I have fixed it and now released it for version 2 and version 3 of the extension.

https://github.com/FriendsOfTYPO3/frontend_editing/releases/tag/2.0.12

https://github.com/FriendsOfTYPO3/frontend_editing/releases/tag/3.0.6
