### ISSUE TITLE
[Feature][PHP 8] PHP 8 compatibility

### ISSUE THREAD

**Issue by guelzow** [FriendsOfTYPO3/frontend_editing#569]
Hi everyone.

"As a web developer I want to use frontend editing together with PHP 8."

AC: The warnings that come from none existing array keys and undefined variables are gone.

Tobi

**Comment by MattiasNilsson** [comment]
@guelzow Hi the extension works with PHP8. Can you provide the errors that you mentioned?

**Comment by guelzow** [comment]
Sure:

PHP Warning: Undefined array key "cms" in /home/www/clients/client1/web17/web/docroot/krexx_dev/typo3_115/docroot/typo3conf/ext/frontend_editing/Classes/Hook/FrontendEditingInitializationHook.php line 445

I'm pretty sure our observability tool will catch others as well.

**Comment by MattiasNilsson** [comment]
@guelzow Thanks, and feel free to add more to this task!
