### ISSUE TITLE
"Permission denied on cross-origin object" when working from another subdomain

### ISSUE THREAD

**Issue by olinox14** [FriendsOfTYPO3/frontend_editing#572]
When the subdomain of the Typo3 BE doesn't match the framed page's subdomain, even if they are subdomains of the same domain, the page won't appear in the fe_editing module, which is loading forever. The following error is logged in the browser console:

`Uncaught DOMException: Permission denied to access property "$" on cross-origin object GUI.js:102`

Browser: Firefox 95.0
Typo3: 10.4.21
Fe editing: 2.0.9

**Comment by MattiasNilsson** [comment]
@olinox14 Thanks for you report we will look into it!

**Comment by hacksch** [comment]
Still with
Firefox: 98
TYPO3: 11.5
Fe Editing: 3.0.15

in our case we use a different subdomain für the backend e.g.

Frontend: www.example.de
Backend: backend.example.de

**Comment by mabolek** [comment]
Related to #547
