### ISSUE TITLE
Error when TSFE is missing

### ISSUE THREAD

**Issue by hacksch** [FriendsOfTYPO3/frontend_editing#573]
PHP 7.4
TYPO3 10.4.22
Frontend_editing: 2.0.9

In my case by a redirect the following error was thrown because TSFE is not present.

 Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 1 passed to TYPO3\CMS\FrontendEditing\Hook\FrontendEditingInitializationHook::isFrontendEditingEnabled() must be an instance of TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController, null given, called in /var/www/htdocs/typo3conf/ext/frontend_editing/Classes/Hook/FrontendEditingInitializationHook.php on line 117 | TypeError thrown in file /var/www/htdocs/typo3conf/ext/frontend_editing/Classes/Hook/FrontendEditingInitializationHook.php in line 136. Requested URL: 

An additional check in the condition of FrontendEditingInitializationHook in line 99 solves that problem
`&& isset($GLOBALS['TSFE'])`

**Comment by MattiasNilsson** [comment]
@hacksch A new release for the v2 have been made: https://github.com/FriendsOfTYPO3/frontend_editing/releases/tag/2.0.1.0
