### ISSUE TITLE
[Bug] Protocol-Handling- Check breaks Iframe-Loading for HTTPS

### ISSUE THREAD

**Issue by typoniels** [FriendsOfTYPO3/frontend_editing#588]
https://github.com/FriendsOfTYPO3/frontend_editing/blob/2933d4d51cf7cdee34e91d76521a929a67dda2aa/Classes/Controller/FrontendEditingModuleController.php#L342

This replacement produces incorrect urls for HTTPS websites in the iframe like **httpss**://domainABC.com

Done with #587

**Comment by MattiasNilsson** [comment]
@typoniels A new release which contains your fix have now been done: https://github.com/FriendsOfTYPO3/frontend_editing/releases/tag/3.0.10
