### ISSUE TITLE
White page in Backend > Frontend Editing module after upgrade to 3.0.12

### ISSUE THREAD

**Issue by sheydin** [FriendsOfTYPO3/frontend_editing#590]
White page every page with TYPO3 11.5.5. Console says:

> Failed to launch 'httpss://<mydomain.com>/page?frontend_editing=true' because the scheme does not have a registered handler.

An additional S is being added to the https. Any idea?

**Comment by MattiasNilsson** [comment]
@sheydin A new version have been published, can you verify that it works for you? https://github.com/FriendsOfTYPO3/frontend_editing/releases/tag/3.0.13

**Comment by sheydin** [comment]
Confirm, the URLs are correct now. Thank you!
