### ISSUE TITLE
HTML code showed when FE edit is activated

### ISSUE THREAD

**Issue by FallenVixtah** [FriendsOfTYPO3/frontend_editing#596]
Noted on BLS industries installation (TYPO3 v9.5)
![frontend editing 9 5](https://user-images.githubusercontent.com/17851084/152126360-f0b677ef-ea07-414b-8aaf-be802bc6fa28.png)

**Comment by FallenVixtah** [comment]
Frontend editing plugin version 1.10.2

**Comment by mabolek** [comment]
This is related to #542. The fix hasn't been backported to the 1.x branch. Upgrading to 2.x would be the best here.
