### ISSUE TITLE
Extension icon under Resources/Public folder for v10

### ISSUE THREAD

**Issue by instruccionesaldorso** [FriendsOfTYPO3/frontend_editing#597]
According to official documentation (see https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/FilesAndLocations/Index.html#reserved-file-names), extension icon should be under Resources/Public/Icons/Extension.svg.
Would you mind moving it to that location, instead of the root of extension /ext_icon.png ?
We're using helhum/typo3-secure-web composer package, to use public resources under public/ and private code under private/ and the fact that the icon is not under Resources/Public/Icons makes it not reachable in the backend module.

**Comment by instruccionesaldorso** [comment]
I saw the change was applied to master branch for v11 compatibility. Could you apply this to branch 2.0.0 as well?

**Comment by MattiasNilsson** [comment]
@instruccionesaldorso A new release is out which fixes your issue: https://github.com/FriendsOfTYPO3/frontend_editing/releases/tag/2.0.14

**Comment by instruccionesaldorso** [comment]
Thank you very much for your support!
