### ISSUE TITLE
Wrong conditions for assigning CSS class t3-frontend-editing__hidden-element

### ISSUE THREAD

**Issue by rbtwt** [FriendsOfTYPO3/frontend_editing#608]
In getContentElementClass (ContentEditbaleWrapperService) the conditions for assigning the hidden class are wrong.

`isset($tcaCtrl) && isset($tcaCtrl['enablecolumns']['disabled']) && isset($row[$tcaCtrl['enablecolumns']['disabled']])`
records with $row['hidden] = 0 get hidden class

`isset($tcaCtrl['enablecolumns']['endtime']) && isset($row[$tcaCtrl['enablecolumns']['endtime']]) &&
            $row[$tcaCtrl['enablecolumns']['endtime']] < GeneralUtility::makeInstance(Context::class)->getPropertyFromAspect('date', 'timestamp')`
records with $row['endtime'] = 0 get hidden class

Version 3.0.17, TYPO3 11.5.9

**Comment by MattiasNilsson** [comment]
@rbtwt A new release with this fix is now out: https://github.com/FriendsOfTYPO3/frontend_editing/releases/tag/3.0.18
