### ISSUE TITLE
Adding new ext:news entries with customDropZone not working

### ISSUE THREAD

**Issue by cdaecke** [FriendsOfTYPO3/frontend_editing#611]
I am not sure, whether I am missing something in my configuration, or this is a bug.

I try to add news entries, by adding the `customDropZone` to my template:

    <core:customDropZone tables="{0:'tx_news_domain_model_news'}" pageUid="6">
    </core:customDropZone>

Now I am dragging a new "custom record" of type "NEWS tx_news_domain_model_news" to the drop zone and nothing happens.  It throws an JavaScript error. When debugging, I can see, that `var newUrlParts = $(ev.currentTarget).data('new-url')` is not defined:

https://github.com/FriendsOfTYPO3/frontend_editing/blob/a0a442aaf575383dcba8e56e182a05df2e43760d/Resources/Public/JavaScript/FrontendEditing.js#L476-L478

Furthermore I can see, that the div for the drop zone looks like this:

    <div class="t3-frontend-editing__dropzone" ondrop="window.parent.F.dropCe(event)" ondragover="window.parent.F.dragCeOver(event)" ondragleave="window.parent.F.dragCeLeave(event)" data-tables="tx_news_domain_model_news" data-pid="6" data-defvals="[]" />

Obviously the `data-new-url` attribute is missing.

And I think the closing div-tag is missing for the custom drop zone.

https://github.com/FriendsOfTYPO3/frontend_editing/blob/a0a442aaf575383dcba8e56e182a05df2e43760d/Classes/Service/ContentEditableWrapperService.php#L333-L337

After the code block above a `$tagBuilder->forceClosingTag(true);` should be added, like in `wrapContentWithDropzone`. Otherwise the frontend view breaks for me.

Environment:
- TYPO3 v10.4.27
- ext:frontend_editing v2.0.14

**Comment by MattiasNilsson** [comment]
@cdaecke A new release is out which addresses the issue.

**Comment by cdaecke** [comment]
@MattiasNilsson Thanks for the fix, but this addresses only the second part of my issue. It still does not add a new record, when dragging a new "custom record" of type "NEWS tx_news_domain_model_news" to the drop zone.

**Comment by MattiasNilsson** [comment]
@cdaecke Have you also configured the Typoscript? https://docs.typo3.org/p/friendsoftypo3/frontend-editing/3.0/en-us/ConfigureAndExtend/TypoScript/Index.html#typoscript-customrecords

**Comment by cdaecke** [comment]
@MattiasNilsson Yes, this is my configuration:

```
config {
  tx_frontendediting {
    customRecordEditing {
      tx_news_pi1 {
        actionName = detail
        recordName = news
        tableName = tx_news_domain_model_news
        listTypeName = news_pi1
      }
    }

    customRecords {
      tx_news_domain_model_news {
        pid = 6
      }
    }

  }
}
```
