### ISSUE TITLE
`customRecords` configuration still available?

### ISSUE THREAD

**Issue by cdaecke** [FriendsOfTYPO3/frontend_editing#629]
Is the `customRecords` configuration, which is [documented here](https://docs.typo3.org/p/friendsoftypo3/frontend-editing/main/en-us/ConfigureAndExtend/TypoScript/Index.html#customrecords), still available, or is the documentation outdated?

When using the following configuration, the news record is saved on the page, where I am creating it.

	config {
		tx_frontendediting {

			customRecords {
				tx_news_domain_model_news {
					pid = 6
				}
			}

		}
	}

With the above configuration, I would expect, that the news record is stored on the page with uid = 6, regardless of the page, which I have selected at the moment of creating the record.

Tested with ext:frontend_editing v2.0.17

**Comment by MattiasNilsson** [comment]
> 

Hi do you have the same issue if you upgrade v3 of the extension?

**Comment by cdaecke** [comment]
@MattiasNilsson I tested now with a fresh system:

TYPO3: v11.5.15
ext:bootstrap_package: v12.0.5
ext:frontend_editing: v3.0.27

In this system `customRecords` are not working at all (not displaying in the right bar). Digging into this issue, I found out, that the `$configuration` holds an array with dots in the array keys, so the key `customRecords` is `customRecords.` which won't work:
https://github.com/FriendsOfTYPO3/frontend_editing/blob/0cf96549ad3c10fb4debe379b58ee4e72423a6db/Classes/Hook/FrontendEditingInitializationHook.php#L502-L506

<img width="1434" alt="Bildschirmfoto 2022-09-05 um 07 29 46" src="https://user-images.githubusercontent.com/2102444/188367364-86a43983-7e9d-4815-b01f-e063ded2cf36.png">

**Comment by cdaecke** [comment]
@MattiasNilsson ... and to answer you question:
No, the configured pid is also not respected with ext:frontend_editing v3.

**Comment by MattiasNilsson** [comment]
@cdaecke A new version out that fixes the issue: https://github.com/FriendsOfTYPO3/frontend_editing/releases/tag/3.0.29
