### ISSUE TITLE
Editing external RTE-Links leaks the frontend_editing URL Parameter 

### ISSUE THREAD

**Issue by rschwemm** [FriendsOfTYPO3/frontend_editing#639]
**Description:**

When editing already persisted external links in a RTE by either double-clicking or the context-menu, the link-browser opens with the URL parameter `frontend_editing=true` appended. If not corrected manually, the parameter will also be persisted and outputted in the FE.

**Workaround:**

Editing the link via the "pen" seems not to have this problem.

**Context:**

The parameter is appended to allow link-navigation within the backend-module: https://github.com/FriendsOfTYPO3/frontend_editing/issues/259 https://github.com/FriendsOfTYPO3/frontend_editing/pull/582 https://github.com/FriendsOfTYPO3/frontend_editing/pull/585

This is done via the HTMLParser, which blindly processes all a-tag-hrefs after the content has been rendered.
The ckeditor (presumably) then picks up the href-value for editing.

**Ideas:**

As navigation is not possible via RTE links as they open the link-browser, they should be excluded from this logic.
Sadly I could not find a sensible way to achieve this.

The HTMLBrowser lacks the context to skip for example a-tags in a contenteditable-div.
The existing data-attribute seems to be set via JS and is not preset at that time.

The ckeditor JS does not seem to provide the hooks for removing URL parameters. 
(Though this is not my cup of tea and I might have missed it.)

Alternatively disabling the double-click-to-edit and context-menu and allowing for link-navigation in RTEs would also solve the problem.

**Comment by rschwemm** [comment]
Hi

could someone acknowledge this as a bug or give otherwise hints, that this is worked on?
If any information is missing, please let me know. I will try my best to fill in the details.

Happy new year :)

**Comment by MattiasNilsson** [comment]
@rschwemm This is a bug.
