### ISSUE TITLE
"Hidden elements" not translatable

### ISSUE THREAD

**Issue by seirerman** [FriendsOfTYPO3/frontend_editing#645]
Just a small thing, but the string "Hidden elements" in the sidebar is hardcoded and not translatable.

Once in RightBarCheckbox.html, twice in RightBar.html.

**Comment by webian** [comment]
This is fixed in release 3.2.0.

Hidden items toggle button moved to module doc header with label:
```
<trans-unit id="top-bar.toggle-hidden-items">
    <source>Show hidden</source>
</trans-unit>
```
