### ISSUE TITLE
CKEditor link browser broken

### ISSUE THREAD

**Issue by EcoGabe** [FriendsOfTYPO3/frontend_editing#650]
Using Typo3 v11 and the latest main (f46f18caec192a24604a3c909fdf8b23d433d7cc)

While this extension is installed, the link browser is broken, even outside of Frontend Editing contexts. Upon selecting a page from the link browser, nothing happens and there are no errors in the console nor backend log. 
![linkbug](https://user-images.githubusercontent.com/60153014/231833664-aca4752b-9e22-43ed-ba13-7f3079b9a489.gif)

**Comment by MattiasNilsson** [comment]
@EcoGabe Which version of TYPO3 v11 are you using? I cant reproduce it on version 11.5.26.

**Comment by EcoGabe** [comment]
11.5.25 but I'll try to update just in case

**Comment by EcoGabe** [comment]
Can confirm it's still happening on 11.5.26

**Comment by EcoGabe** [comment]
https://github.com/FriendsOfTYPO3/frontend_editing/blob/14ea6b27174f281634cd2e0295e0ce6ea2ae045f/ext_localconf.php#L5-L8

```patch 
@@ -4,7 +4,7 @@ defined('TYPO3') or die();
 
 if (TYPO3_MODE === 'BE') {
     $pageRenderer = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Core\Page\PageRenderer::class);
-    $pageRenderer->loadRequireJsModule('TYPO3/CMS/FrontendEditing/ParentWindow');
+    // $pageRenderer->loadRequireJsModule('TYPO3/CMS/FrontendEditing/ParentWindow');
 }
 
 // Extend the <core:contentEditable> viewhelper by the one from EXT:frontend_editing
```

Removing this code fixes the problem, but it looks like the point of loading ParentWindow.js is to resolve a [different issue](#457).

**Comment by cdaecke** [comment]
I can confirm this issue, but just with Safari. On Firefox it works without any problems.

Reproduce this issue with Safari:

- edit a text element (without frontend editing)
- mark a word
- click on link icon
- select a page in the "Link Browser" by clicking on the chain symbol

After that, the "Link Browser" is closed, but the link is not inserted into the RTE. The text is still marked.


TYPO3 v11.5.26
frontend_editing v3.0.35

**Comment by mueller-sebastian** [comment]
I can confirm this issue too. 
Sometimes (but rarely) it works. If you open the RTE and try to insert 5 links, may one will succeed.

Testet with Chrome in TYPO3 v 11.5.26 and latest frontend_editing.
Testet with Record / RTE opened directly in page module (not via fronend editing module).

It also occures for admins so it has nothing to do with user rights.
There are no js errors displayed in browser dev-tools.

When uninstalling frontend_editing it works again as it should.

**Comment by MattiasNilsson** [comment]
A new release is out which fixes the issue: https://github.com/FriendsOfTYPO3/frontend_editing/releases/tag/3.0.36

**Comment by cdaecke** [comment]
@MattiasNilsson Thanks for your work and the new release!

Unfortunately the issue is not fixed for me (browser cache was cleared).

**Comment by MattiasNilsson** [comment]
I had the revert the last fix and a new release is out which disables the CKEditor fixes. But I will investigate how to solve it. We are open for all contributions regarding this!

https://github.com/FriendsOfTYPO3/frontend_editing/releases/tag/3.0.37

**Comment by EcoGabe** [comment]
On EcoGabe@9e9e6dd782e82890264a8bc560aea9035956954e, I listen for [BootCompletedEvent](https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/Events/Events/Core/Core/BootCompletedEvent.html), which seems to load the RequireJS module without breaking Chrome. However, I'm unsure of Firefox's behavior since that's been broken for me regardless of RequireJS.

**Comment by MattiasNilsson** [comment]
A new release is out which fixes the issue: https://github.com/FriendsOfTYPO3/frontend_editing/releases/tag/3.0.38
