### ISSUE TITLE
Frontend loads twice in frontend_editing module

### ISSUE THREAD

**Issue by webian** [FriendsOfTYPO3/frontend_editing#675]
In the frontend_editing module, the website frontend is always loaded 2 times. If I remember correctly, it was necessary to load it 2 times before version 2.0. Is it still necessary in version > 2?

**Comment by MattiasNilsson** [comment]
@webian Not really sure in which case you mean? Is it in the iframe of the backend module that is loads twice? Because there is 1 page request and then an AJAX request on top of that.

**Comment by webian** [comment]
Yes, it is loaded twice in the iframe of the backendmodule.
Can you help me to understand the reason of the second AJAX request?
Because, debugging, I tried to wrap my head around this but I failed.

**Comment by MattiasNilsson** [comment]
@webian So basically we fetch the page as it is with the Frontend Editing wrapping and content editables. Then we need to fetch the resources (Javascript etc) so be able to interact with the website.

But there is still only 1 page request being made.

![Screenshot 2023-07-31 at 11 06 42](https://github.com/FriendsOfTYPO3/frontend_editing/assets/1718315/2ff4af8d-0d30-4384-9bfa-a2fdd4370a0f)

**Comment by webian** [comment]
That screenshot display the network filtered by "FrontendEditing" and displays the module request.
Then the module makes 2 requests of the frontend page:
![o0koiojh](https://github.com/FriendsOfTYPO3/frontend_editing/assets/462601/ad000f90-71d5-4f08-8bb7-aedd739ae708)
