### ISSUE TITLE
Custom records in right bar are in the wrong place

### ISSUE THREAD

**Issue by webian** [FriendsOfTYPO3/frontend_editing#689]
Actually, in the right bar, the custom records icons appear after the "Elements on page".

I think it is more logical if the custom records would appear immediately after the list of content element.

Also, what is the purpose of "Elements on page"? Is that still needed now that frontend editing is inside the backend?
If not, I can solve this bug removing "Elements on page" from the right bar.

I wait for your feedback.

**Comment by MattiasNilsson** [comment]
@webian You can go ahead and remove the "Elements on page" functionality.
