### ISSUE TITLE
ContentObjectRenderer Xclass always set $editUid=1 for localized CE

### ISSUE THREAD

**Issue by webian** [FriendsOfTYPO3/frontend_editing#693]
https://github.com/FriendsOfTYPO3/frontend_editing/blob/7c248c870bc2cf80a8d2041cdaf6e02f5c05f701/Classes/Xclass/ContentObject/ContentObjectRenderer.php#L54

If $dataArray['_LOCALIZED_UID'] is set, $editUid will always be 1 but should instead be the uid of the localized record.

The description of this commit https://github.com/FriendsOfTYPO3/frontend_editing/pull/579/commits/bbb805eea8c1eaec3065cc6ba8d890252a1e2224 is "[TASK] Add Xclass for handling PHP 8 in ContentObjectRenderer"

What's the purpose of this xclass @MattiasNilsson?

**Comment by MattiasNilsson** [comment]
@webian The whole purpose of the XCLASS was to add isset($dataArray['_LOCALIZED_UID']) for PHP8. It could be that the part is fixed in the core. Then that means that the XCLASS can be removed without any hassle.

**Comment by webian** [comment]
I opened a bug report in TYPO3 core
https://forge.typo3.org/issues/101602

and made a PR to fix this bug.
