### ISSUE TITLE
Getting error 503 with bootstrap_package

### ISSUE THREAD

**Issue by sheydin** [FriendsOfTYPO3/frontend_editing#733]
Hello, every frontend editing view gives me 503 with TYPO3 11.5.28 and frontend_editing 4.0.7:

<img width="1445" alt="Bildschirmfoto 2023-10-14 um 18 34 52" src="https://github.com/FriendsOfTYPO3/frontend_editing/assets/2332612/f2b41863-ee9f-4cc3-98c8-bb4723ce5a65">

Please help.

**Comment by webian** [comment]
Try to dump autoload [2] and flush caches [3]
![fwxff1qi](https://github.com/FriendsOfTYPO3/frontend_editing/assets/462601/e4254d1d-2295-42c9-afa3-31681aead007)

If it doesn't work, please provide the stack trace of the error.

**Comment by sheydin** [comment]
Thanks webian, works after resetting all the cache, only in Chrome though. This is what I get in Safari:

<img width="1697" alt="Bildschirmfoto 2023-10-15 um 12 08 43" src="https://github.com/FriendsOfTYPO3/frontend_editing/assets/2332612/d028cecc-025c-4450-94a9-8c2f19f9e43f">

When I drag the whole area, the actual page representation appears underneath.

The inline editing feature is gone now?

**Comment by webian** [comment]
Clear also Safari cache for the website.
