### ISSUE TITLE
Broken view in backend

### ISSUE THREAD

**Issue by ademas02** [FriendsOfTYPO3/frontend_editing#737]
Updating higher than v. 3.3.4 I get only this in the backend
![fe](https://github.com/FriendsOfTYPO3/frontend_editing/assets/44165451/e792afd8-36ad-4c3a-99be-5047a40f0294)

**Comment by webian** [comment]
Did you try to clear browser cache?

**Comment by ademas02** [comment]
That's the solution. Thanks!
